import figma from "@images/icons/project-icons/figma.png";
import sketch from "@images/icons/project-icons/sketch.png";
import vue from "@images/icons/project-icons/vue.png";
import type { JobProperties } from "./types";

interface DB {
  jobs: JobProperties[];
}

export const db: DB = {
  jobs: [
    {
      id: 1,
      jobOrderNumber: "JO26/001",
      name: "Workplace Activation Package",
      code: "DL03",
      avatar: figma,
      startDate: "2026-06-23T09:00:00Z",
      endDate: "2026-10-31T17:00:00Z",
      location: "Online",
      stage: "In Progress",
      status: "In Progress",
      type: "Other",
      flag: "High",
      relatedTo: 3,
      projectManagerId: 7,
      collaborators: [7, 8, 5],
      note: "Fast turnaround requested for workplace planning and activation.",
      stakeholders: [
        { id: 1, contactId: 3, role: "Client" },
        { id: 2, contactId: 1, role: "Key Contact" },
        { id: 3, contactId: 4, role: "Operations Lead" },
      ],
      milestones: [
        {
          id: 1,
          name: "Workplace Acoustic Consulting Retainer",
          startDate: "2026-06-23T09:00:00Z",
          dueDate: "2026-07-31T17:00:00Z",
          priority: "High",
          note: "Monthly consulting retainer for workplace planning and review.",
        },
        {
          id: 2,
          name: "Monthly Meeting Pod Cleaning Service",
          startDate: "2026-07-01T09:00:00Z",
          dueDate: "2026-10-31T17:00:00Z",
          priority: "Normal",
          note: "Recurring cleaning and upkeep service for enclosed meeting pods.",
        },
      ],
      goals: [
        {
          id: 1,
          milestoneId: 1,
          name: "Confirm acoustic review checklist",
          startDate: "2026-06-24T09:00:00Z",
          dueDate: "2026-07-15T17:00:00Z",
          priority: "High",
          note: "Review rooms, circulation paths, and consultant comments.",
        },
        {
          id: 2,
          milestoneId: 2,
          name: "Lock recurring cleaning calendar",
          startDate: "2026-07-01T09:00:00Z",
          dueDate: "2026-08-05T17:00:00Z",
          priority: "Normal",
          note: "Confirm access windows before recurring service begins.",
        },
      ],
      documents: [
        {
          id: 1,
          category: "PDF",
          type: "Contract",
          name: "Workplace Activation Agreement",
          note: "Converted job agreement",
          fileUrl: "/documents/workplace-activation-agreement.pdf",
          createdAt: "2026-06-23T12:00:00Z",
        },
      ],
      createdAt: "2026-06-23T12:00:00Z",
    },
    {
      id: 2,
      jobOrderNumber: "JO26/002",
      name: "Expo Pavilion Stand",
      code: "EV-204",
      avatar: sketch,
      startDate: "2026-07-01T08:00:00Z",
      endDate: "2026-08-18T20:00:00Z",
      location: "Doha, Qatar",
      stage: "Pending",
      status: "Pending",
      type: "Stands & Events",
      flag: "High",
      relatedTo: 5,
      projectManagerId: 7,
      collaborators: [7, 8, 4],
      note: "Design and delivery of an expo stand with lighting and visitor-flow coordination.",
      stakeholders: [
        { id: 1, contactId: 5, role: "Client" },
        { id: 2, contactId: 2, role: "Client Representative" },
        { id: 3, contactId: 8, role: "Regional Manager" },
      ],
      milestones: [
        {
          id: 1,
          name: "Technical Drawings Approval",
          startDate: "2026-07-01T09:00:00Z",
          dueDate: "2026-07-20T17:00:00Z",
          priority: "High",
          note: "Confirm dimensions, rigging points, and venue restrictions.",
        },
        {
          id: 2,
          name: "Stand Installation Handover",
          startDate: "2026-08-01T07:30:00Z",
          dueDate: "2026-08-18T20:00:00Z",
          priority: "High",
          note: "Complete snagging and handover before expo opening.",
        },
      ],
      goals: [
        {
          id: 1,
          milestoneId: 1,
          name: "Issue production drawing pack",
          startDate: "2026-07-08T09:00:00Z",
          dueDate: "2026-07-18T17:00:00Z",
          priority: "High",
          note: "Send final pack for client and venue approval.",
        },
        {
          id: 2,
          milestoneId: 2,
          name: "Prepare handover checklist",
          startDate: "2026-08-10T09:00:00Z",
          dueDate: "2026-08-16T17:00:00Z",
          priority: "Normal",
          note: "Include AV, electrical, and branding checks.",
        },
      ],
      documents: [],
      createdAt: "2026-06-10T10:15:00Z",
    },
    {
      id: 3,
      jobOrderNumber: "JO26/003",
      name: "Residence Interior Renovation",
      code: "LH-310",
      avatar: vue,
      startDate: "2026-08-03T09:30:00Z",
      endDate: "2026-11-12T17:00:00Z",
      location: "Beirut, Lebanon",
      stage: "New",
      status: "New",
      type: "Interior",
      flag: "Normal",
      relatedTo: 1,
      projectManagerId: 5,
      collaborators: [5, 6, 10],
      note: "Residential renovation currently awaiting project-owner kickoff.",
      stakeholders: [
        { id: 1, contactId: 1, role: "Client" },
        { id: 2, contactId: 6, role: "Legal Advisor" },
        { id: 3, contactId: 9, role: "Financial Analyst" },
      ],
      milestones: [
        {
          id: 1,
          name: "Concept Direction",
          startDate: "2026-08-03T10:00:00Z",
          dueDate: "2026-09-10T16:00:00Z",
          priority: "Normal",
          note: "Agree room-by-room design direction before detailed layouts.",
        },
        {
          id: 2,
          name: "Material Selection",
          startDate: "2026-09-14T09:00:00Z",
          dueDate: "2026-10-15T17:00:00Z",
          priority: "Normal",
          note: "Confirm finishes, fixtures, and procurement lead times.",
        },
      ],
      goals: [
        {
          id: 1,
          milestoneId: 1,
          name: "Kickoff with client",
          startDate: "2026-08-03T09:30:00Z",
          dueDate: "2026-08-07T17:00:00Z",
          priority: "Normal",
          note: "Confirm brief, budget, and decision schedule.",
        },
      ],
      documents: [
        {
          id: 1,
          category: "PDF",
          type: "Proposals",
          name: "Interior Renovation Proposal",
          note: "Approved renovation scope and commercial terms",
          fileUrl: "/documents/interior-renovation-proposal.pdf",
          createdAt: "2026-06-18T09:30:00Z",
        },
      ],
      createdAt: "2026-06-18T14:45:00Z",
    },
  ],
};
