import figma from "@images/icons/project-icons/figma.png";
import sketch from "@images/icons/project-icons/sketch.png";
import vue from "@images/icons/project-icons/vue.png";
import type { JobProperties } from "./types";

interface DB {
  jobs: JobProperties[];
}
export const db: DB = {
  jobs: [
    {
      id: 1,
      name: "Ted's Project",
      code: "P-1234",
      avatar: figma,
      startDate: "2024-04-01T09:00:00Z",
      endDate: "2024-08-15T17:00:00Z",
      location: "Beirut, Lebanon",
      stage: "PRPSL",
      type: "Architecture",
      flag: "Normal",
      relatedTo: 1,
      collaborators: [1, 3, 6],
      note: "Concept development for mixed-use complex with hospitality component.",
      stakeholders: [
        { id: 1, contactId: 1, role: "Client" },
        { id: 2, contactId: 3, role: "Owner" },
        { id: 3, contactId: 6, role: "Legal Advisor" },
      ],
      milestones: [
        {
          id: 1,
          name: "Concept Sign-off",
          startDate: "2024-04-05T09:00:00Z",
          dueDate: "2024-05-10T17:00:00Z",
          priority: "High",
          note: "Secure board approval on concept package.",
        },
        {
          id: 2,
          name: "Detailed Design",
          startDate: "2024-05-15T09:00:00Z",
          dueDate: "2024-07-30T17:00:00Z",
          priority: "Normal",
          note: "Coordinate with structural and MEP teams.",
        },
      ],
      goals: [
        {
          id: 1,
          milestoneId: 1,
          name: "Present revised concept",
          startDate: "2024-04-20T09:00:00Z",
          dueDate: "2024-04-25T17:00:00Z",
          priority: "High",
          note: "Include updated façade studies.",
        },
        {
          id: 2,
          milestoneId: 2,
          name: "Issue IFC package",
          startDate: "2024-07-01T08:30:00Z",
          dueDate: "2024-07-25T17:30:00Z",
          priority: "Normal",
          note: "Align drawings with latest BIM model.",
        },
      ],
      documents: [
        {
          id: 1,
          category: "PDF",
          type: "Contract",
          name: "Project Agreement",
          note: "Main contract document",
          fileUrl: "/documents/project-agreement.pdf",
          createdAt: "2024-03-28T12:00:00Z",
        },
        {
          id: 2,
          category: "PDF",
          type: "Proposals",
          name: "Initial Concept Proposal",
          note: "First design proposal submitted to client",
          fileUrl: "/documents/concept-proposal.pdf",
          createdAt: "2024-04-01T10:00:00Z",
        },
      ],
      createdAt: "2024-03-28T12:00:00Z",
    },
    {
      id: 2,
      name: "Expo Pavilion",
      code: "EV-204",
      avatar: sketch,
      startDate: "2024-02-12T08:00:00Z",
      endDate: "2024-04-10T20:00:00Z",
      location: "Dubai, UAE",
      stage: "Project | In Progress",
      type: "Stands & Events",
      flag: "High",
      relatedTo: 5,
      collaborators: [2, 5, 8],
      note: "Immersive pavilion for tech expo with interactive lighting.",
      stakeholders: [
        { id: 1, contactId: 5, role: "Primary Sponsor" },
        { id: 2, contactId: 2, role: "Client Representative" },
        { id: 3, contactId: 8, role: "Regional Manager" },
      ],
      milestones: [
        {
          id: 1,
          name: "Structure Installation",
          startDate: "2024-03-01T07:30:00Z",
          dueDate: "2024-03-15T18:00:00Z",
          priority: "High",
          note: "Coordinate with venue contractor on overnight shifts.",
        },
        {
          id: 2,
          name: "Experience Testing",
          startDate: "2024-03-20T09:00:00Z",
          dueDate: "2024-04-05T20:00:00Z",
          priority: "High",
          note: "Finalize AV integration and visitor flow.",
        },
      ],
      goals: [
        {
          id: 1,
          milestoneId: 2,
          name: "Soft launch walkthrough",
          startDate: "2024-03-28T10:00:00Z",
          dueDate: "2024-03-30T19:00:00Z",
          priority: "High",
          note: "Invite sponsors for preview feedback.",
        },
        {
          id: 2,
          milestoneId: 2,
          name: "Handover to operations",
          startDate: "2024-04-04T09:00:00Z",
          dueDate: "2024-04-05T17:00:00Z",
          priority: "Normal",
          note: "Deliver training manuals and orientation.",
        },
      ],
      documents: [],
      createdAt: "2024-02-01T10:15:00Z",
    },
    {
      id: 3,
      name: "Headquarters Renovation",
      code: "INT-88",
      avatar: vue,
      startDate: "2024-06-10T09:30:00Z",
      endDate: "2024-09-30T17:00:00Z",
      location: "Doha, Qatar",
      stage: "In Review",
      type: "Interior",
      flag: "Low",
      relatedTo: 3,
      collaborators: [3, 7, 9],
      note: "Phased renovation of executive floors while occupied.",
      stakeholders: [
        { id: 1, contactId: 3, role: "Owner" },
        { id: 2, contactId: 7, role: "Operations Lead" },
        { id: 3, contactId: 9, role: "Financial Analyst" },
      ],
      milestones: [
        {
          id: 1,
          name: "Material Sign-off",
          startDate: "2024-06-15T10:00:00Z",
          dueDate: "2024-06-28T16:00:00Z",
          priority: "Normal",
          note: "Confirm finishes with procurement.",
        },
        {
          id: 2,
          name: "Phase 1 Delivery",
          startDate: "2024-07-05T09:00:00Z",
          dueDate: "2024-08-18T17:00:00Z",
          priority: "Normal",
          note: "Relocate staff temporarily to annex.",
        },
      ],
      goals: [
        {
          id: 1,
          milestoneId: 2,
          name: "Executive wing handover",
          startDate: "2024-08-12T08:00:00Z",
          dueDate: "2024-08-18T18:00:00Z",
          priority: "Normal",
          note: "Coordinate snagging with facility team.",
        },
      ],
      documents: [
        {
          id: 1,
          category: "PDF",
          type: "Proposals",
          name: "Renovation Proposal",
          note: "Phased renovation plan and timeline",
          fileUrl: "/documents/renovation-proposal.pdf",
          createdAt: "2024-06-10T09:30:00Z",
        },
      ],
      createdAt: "2024-05-20T14:45:00Z",
    },
  ],
};
