import avatar1 from "@images/avatars/avatar-1.png";
import avatar2 from "@images/avatars/avatar-2.png";
import avatar4 from "@images/avatars/avatar-4.png";
import avatar5 from "@images/avatars/avatar-5.png";
import avatar6 from "@images/avatars/avatar-6.png";

import type { ContactProperties } from "./types";

interface DB {
  users: ContactProperties[];
}

export const db: DB = {
  users: [
    {
      id: 1,
      fullName: "Lina Haddad",
      class: "Lead",
      type: "Individual",
      category: "VIP",
      email: "lina.haddad@example.com",
      number: "+961 70 123 456",
      status: "Active",
      picture: avatar1,
      connections: [
        {
          contactId: 3,
          contactName: "Squarely HQ",
          isPrimary: true,
          relation: "Account Manager",
        },
        {
          contactId: 6,
          contactName: "Daniel Smith",
          isPrimary: false,
          relation: "Legal Advisor",
        },
      ],
      accounting: {
        taxId: "LB-123456",
        crn: "CRN-9981",
        vatNumber: "VAT-112233",
      },
      address: "123 Downtown Street",
      poBox: "POB 2245",
      country: "Lebanon",
      city: "Beirut",
      language: "Arabic",
      channel: "Referral",
      birthdate: "1987-04-15",
      worksInSales: true,
      createdAt: "2024-09-01T09:00:00Z",
    },
    {
      id: 2,
      fullName: "Farah Mansour",
      class: "Client",
      type: "Entity",
      category: "Real Estate",
      email: "client.services@cedarholdings.com",
      number: "+971 4 445 2233",
      status: "Active",
      picture: avatar2,
      connections: [
        {
          contactId: 5,
          contactName: "Align Brokerage",
          isPrimary: true,
          relation: "Primary Broker",
        },
        {
          contactId: 9,
          contactName: "Imad Khoury",
          isPrimary: false,
          relation: "Financial Analyst",
        },
      ],
      accounting: {
        taxId: "AE-449120",
        crn: "CRN-2045",
        vatNumber: "VAT-554433",
      },
      address: "Jumeirah 3, Commercial Tower 9",
      poBox: "POB 82311",
      country: "United Arab Emirates",
      city: "Dubai",
      language: "English",
      channel: "Direct Sales",
      birthdate: undefined,
      worksInSales: false,
      createdAt: "2024-08-24T10:00:00Z",
    },
    {
      id: 3,
      fullName: "Squarely HQ",
      class: "Owner",
      type: "Entity",
      category: "General",
      email: "hq@squarely.com",
      number: "+961 1 556 990",
      status: "Active",
      picture: "",
      connections: [
        {
          contactId: 1,
          contactName: "Lina Haddad",
          isPrimary: true,
          relation: "Key Contact",
        },
        {
          contactId: 4,
          contactName: "Nour Yazbek",
          isPrimary: false,
          relation: "Operations Lead",
        },
      ],
      accounting: {
        taxId: "LB-001245",
        crn: "CRN-1000",
        vatNumber: "VAT-009911",
      },
      address: "Squarely Center, Level 11",
      poBox: "POB 1100",
      country: "Lebanon",
      city: "Beirut",
      language: "Arabic",
      channel: "Website",
      birthdate: undefined,
      worksInSales: true,
      createdAt: "2024-08-18T08:30:00Z",
    },
    {
      id: 4,
      fullName: "Nour Yazbek",
      class: "Contact",
      type: "Individual",
      category: "General",
      email: "nour.yazbek@squarely.com",
      number: "+961 3 782 120",
      status: "Potential",
      picture: avatar4,
      connections: [
        {
          contactId: 3,
          contactName: "Squarely HQ",
          isPrimary: true,
          relation: "Employer",
        },
        {
          contactId: 7,
          contactName: "Mona Darwich",
          isPrimary: false,
          relation: "Personal Mentor",
        },
      ],
      accounting: {},
      address: "Ashrafieh, Building 24",
      poBox: "",
      country: "Lebanon",
      city: "Beirut",
      language: "French",
      channel: "Email Campaigns",
      birthdate: "1992-11-08",
      worksInSales: false,
      createdAt: "2024-07-28T14:15:00Z",
    },
    {
      id: 5,
      fullName: "Align Brokerage",
      class: "Supplier",
      type: "Entity",
      category: "General",
      email: "info@alignbrokerage.co",
      number: "+974 6 221 4455",
      status: "Active",
      picture: avatar5,
      connections: [
        {
          contactId: 2,
          contactName: "Farah Mansour",
          isPrimary: true,
          relation: "Primary Client",
        },
        {
          contactId: 8,
          contactName: "Rania Abdul",
          isPrimary: false,
          relation: "Regional Manager",
        },
      ],
      accounting: {
        taxId: "QA-552310",
        crn: "CRN-7412",
        vatNumber: "VAT-773377",
      },
      address: "Pearl District, Tower 2",
      poBox: "POB 43111",
      country: "Qatar",
      city: "Doha",
      language: "Arabic",
      channel: "Referral",
      birthdate: undefined,
      worksInSales: true,
      createdAt: "2024-07-10T11:45:00Z",
    },
    {
      id: 6,
      fullName: "Daniel Smith",
      class: "Lead",
      type: "Individual",
      category: "VIP",
      email: "daniel.smith@consultly.io",
      number: "+44 20 8555 2015",
      status: "Dormant",
      picture: avatar6,
      connections: [
        {
          contactId: 1,
          contactName: "Lina Haddad",
          isPrimary: true,
          relation: "Prospect Owner",
        },
        {
          contactId: 9,
          contactName: "Imad Khoury",
          isPrimary: false,
          relation: "Analyst",
        },
      ],
      accounting: {
        vatNumber: "VAT-881122",
      },
      address: "21 Baker Street",
      poBox: "",
      country: "United Kingdom",
      city: "London",
      language: "English",
      channel: "Email Campaigns",
      birthdate: "1981-06-22",
      worksInSales: true,
      createdAt: "2024-06-22T13:20:00Z",
    },
    {
      id: 7,
      fullName: "Mona Darwich",
      class: "Contact",
      type: "Individual",
      category: "Real Estate",
      email: "mona.darwich@elevatehomes.me",
      number: "+961 71 220 045",
      status: "Potential",
      picture: avatar2,
      connections: [
        {
          contactId: 4,
          contactName: "Nour Yazbek",
          isPrimary: true,
          relation: "Consultant",
        },
        {
          contactId: 10,
          contactName: "Yara Ghandour",
          isPrimary: false,
          relation: "Partner",
        },
      ],
      accounting: {
        taxId: "LB-778800",
        crn: "CRN-5611",
        vatNumber: "VAT-334455",
      },
      address: "Dbayeh Highway, Bloc 6",
      poBox: "POB 5522",
      country: "Lebanon",
      city: "Dbayeh",
      language: "Arabic",
      channel: "Social Media",
      birthdate: "1990-02-01",
      worksInSales: true,
      createdAt: "2024-06-05T10:10:00Z",
    },
    {
      id: 8,
      fullName: "Rania Abdul",
      class: "Supplier",
      type: "Individual",
      category: "General",
      email: "rania.abdul@alignbrokerage.co",
      number: "+974 5 668 1200",
      status: "Active",
      picture: avatar4,
      connections: [
        {
          contactId: 5,
          contactName: "Align Brokerage",
          isPrimary: true,
          relation: "Employer",
        },
        {
          contactId: 2,
          contactName: "Farah Mansour",
          isPrimary: false,
          relation: "Key Client",
        },
      ],
      accounting: {
        taxId: "QA-991122",
        crn: "CRN-2255",
        vatNumber: "VAT-667788",
      },
      address: "The Gate Mall Offices",
      poBox: "",
      country: "Qatar",
      city: "Doha",
      language: "English",
      channel: "Direct Sales",
      birthdate: "1984-09-18",
      worksInSales: true,
      createdAt: "2024-05-18T09:05:00Z",
    },
    {
      id: 9,
      fullName: "Imad Khoury",
      class: "Contact",
      type: "Individual",
      category: "VIP",
      email: "imad.khoury@financepros.co",
      number: "+961 1 880 441",
      status: "Dormant",
      picture: avatar5,
      connections: [
        {
          contactId: 2,
          contactName: "Farah Mansour",
          isPrimary: true,
          relation: "Client",
        },
        {
          contactId: 6,
          contactName: "Daniel Smith",
          isPrimary: false,
          relation: "Colleague",
        },
      ],
      accounting: {
        taxId: "LB-445566",
        crn: "CRN-3322",
        vatNumber: "VAT-221144",
      },
      address: "Verdun Street 12",
      poBox: "POB 7788",
      country: "Lebanon",
      city: "Beirut",
      language: "Arabic",
      channel: "Referral",
      birthdate: "1979-01-10",
      worksInSales: false,
      createdAt: "2024-04-12T16:25:00Z",
    },
    {
      id: 10,
      fullName: "Yara Ghandour",
      class: "Client",
      type: "Individual",
      category: "VIP",
      email: "yara.ghandour@luxproperties.me",
      number: "+961 70 888 102",
      status: "Lost",
      picture: avatar6,
      connections: [
        {
          contactId: 7,
          contactName: "Mona Darwich",
          isPrimary: true,
          relation: "Partner",
        },
        {
          contactId: 1,
          contactName: "Lina Haddad",
          isPrimary: false,
          relation: "Advisor",
        },
      ],
      accounting: {
        vatNumber: "VAT-909090",
      },
      address: "Furn El Chebbak, Block 4",
      poBox: "",
      country: "Lebanon",
      city: "Beirut",
      language: "Arabic",
      channel: "Social Media",
      birthdate: "1988-08-30",
      worksInSales: false,
      createdAt: "2024-03-20T11:35:00Z",
    },
  ],
};
