import avatar1 from "@images/avatars/avatar-1.png";
import avatar2 from "@images/avatars/avatar-2.png";
import avatar3 from "@images/avatars/avatar-3.png";
import avatar4 from "@images/avatars/avatar-4.png";
import avatar5 from "@images/avatars/avatar-5.png";
import avatar6 from "@images/avatars/avatar-6.png";

import type { ContactProperties } from "./types";

interface DB {
  users: ContactProperties[];
}

export const db: DB = {
  users: [
    {
      id: 1,
      fullName: "Lina Haddad",
      class: "Lead",
      roles: ["client"],
      type: "Individual",
      category: "VIP",
      email: "lina.haddad@example.com",
      number: "+961 70 123 456",
      status: "Active",
      picture: avatar1,
      connections: [
        {
          contactId: 3,
          contactName: "Squarely HQ",
          isPrimary: true,
          relation: "Account Manager",
        },
        {
          contactId: 6,
          contactName: "Daniel Smith",
          isPrimary: false,
          relation: "Legal Advisor",
        },
      ],
      accounting: {
        taxId: "LB-123456",
        crn: "CRN-9981",
        vatNumber: "VAT-112233",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "123 Downtown Street",
      country: "Lebanon",
      city: "Beirut",
      language: "Arabic",
      channel: "Referral",
      website: "https://lina.example.com",
      birthdate: "1987-04-15",
      worksInSales: true,
      createdAt: "2024-09-01T09:00:00Z",
    },
    {
      id: 2,
      fullName: "Farah Mansour",
      class: "Client",
      roles: ["client"],
      type: "Entity",
      category: "Real Estate",
      email: "client.services@cedarholdings.com",
      number: "+971 4 445 2233",
      status: "Active",
      picture: avatar2,
      connections: [
        {
          contactId: 5,
          contactName: "Align Brokerage",
          isPrimary: true,
          relation: "Primary Broker",
        },
        {
          contactId: 9,
          contactName: "Imad Khoury",
          isPrimary: false,
          relation: "Financial Analyst",
        },
      ],
      accounting: {
        taxId: "AE-449120",
        crn: "CRN-2045",
        vatNumber: "VAT-554433",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "Jumeirah 3, Commercial Tower 9",
      country: "United Arab Emirates",
      city: "Dubai",
      language: "English",
      channel: "Direct Sales",
      website: "https://cedarholdings.com",
      birthdate: undefined,
      worksInSales: false,
      createdAt: "2024-08-24T10:00:00Z",
    },
    {
      id: 3,
      fullName: "Squarely HQ",
      class: "Owner",
      roles: ["client"],
      type: "Entity",
      category: "General",
      email: "hq@squarely.com",
      number: "+961 1 556 990",
      status: "Active",
      picture: "",
      connections: [
        {
          contactId: 1,
          contactName: "Lina Haddad",
          isPrimary: true,
          relation: "Key Contact",
        },
        {
          contactId: 4,
          contactName: "Nour Yazbek",
          isPrimary: false,
          relation: "Operations Lead",
        },
      ],
      accounting: {
        taxId: "LB-001245",
        crn: "CRN-1000",
        vatNumber: "VAT-009911",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "Squarely Center, Level 11",
      country: "Lebanon",
      city: "Beirut",
      language: "Arabic",
      channel: "Website",
      website: "https://squarely.com",
      birthdate: undefined,
      worksInSales: true,
      createdAt: "2024-08-18T08:30:00Z",
    },
    {
      id: 4,
      fullName: "Nour Yazbek",
      class: "Contact",
      type: "Individual",
      category: "General",
      email: "nour.yazbek@squarely.com",
      number: "+961 3 782 120",
      status: "Potential",
      picture: avatar4,
      connections: [
        {
          contactId: 3,
          contactName: "Squarely HQ",
          isPrimary: true,
          relation: "Employer",
        },
        {
          contactId: 7,
          contactName: "Mona Darwich",
          isPrimary: false,
          relation: "Personal Mentor",
        },
      ],
      accounting: {},
      documents: [],
      records: [],
      transactions: [],
      address: "Ashrafieh, Building 24",
      country: "Lebanon",
      city: "Beirut",
      language: "French",
      channel: "Email Campaigns",
      birthdate: "1992-11-08",
      worksInSales: false,
      createdAt: "2024-07-28T14:15:00Z",
    },
    {
      id: 5,
      fullName: "Align Brokerage",
      class: "Supplier",
      roles: ["client", "supplier"],
      type: "Entity",
      category: "General",
      email: "info@alignbrokerage.co",
      number: "+974 6 221 4455",
      status: "Active",
      picture: avatar5,
      connections: [
        {
          contactId: 2,
          contactName: "Farah Mansour",
          isPrimary: true,
          relation: "Primary Client",
        },
        {
          contactId: 8,
          contactName: "Rania Abdul",
          isPrimary: false,
          relation: "Regional Manager",
        },
      ],
      accounting: {
        taxId: "QA-552310",
        crn: "CRN-7412",
        vatNumber: "VAT-773377",
      },
      documents: [],
      address: "Pearl District, Tower 2",
      country: "Qatar",
      city: "Doha",
      language: "Arabic",
      channel: "Referral",
      website: "https://alignbrokerage.co",
      birthdate: undefined,
      worksInSales: true,
      createdAt: "2024-07-10T11:45:00Z",
    },
    {
      id: 6,
      fullName: "Daniel Smith",
      class: "Lead",
      type: "Individual",
      category: "VIP",
      email: "daniel.smith@consultly.io",
      number: "+44 20 8555 2015",
      status: "Dormant",
      picture: avatar6,
      connections: [
        {
          contactId: 1,
          contactName: "Lina Haddad",
          isPrimary: true,
          relation: "Prospect Owner",
        },
        {
          contactId: 9,
          contactName: "Imad Khoury",
          isPrimary: false,
          relation: "Analyst",
        },
      ],
      accounting: {
        vatNumber: "VAT-881122",
      },
      documents: [],
      address: "21 Baker Street",

      country: "United Kingdom",
      city: "London",
      language: "English",
      channel: "Email Campaigns",
      birthdate: "1981-06-22",
      worksInSales: true,
      createdAt: "2024-06-22T13:20:00Z",
    },
    {
      id: 7,
      fullName: "Mona Darwich",
      class: "Contact",
      roles: ["client"],
      type: "Individual",
      category: "Real Estate",
      email: "mona.darwich@elevatehomes.me",
      number: "+961 71 220 045",
      status: "Potential",
      picture: avatar2,
      connections: [
        {
          contactId: 4,
          contactName: "Nour Yazbek",
          isPrimary: true,
          relation: "Consultant",
        },
        {
          contactId: 10,
          contactName: "Yara Ghandour",
          isPrimary: false,
          relation: "Partner",
        },
      ],
      accounting: {
        taxId: "LB-778800",
        crn: "CRN-5611",
        vatNumber: "VAT-334455",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "Dbayeh Highway, Bloc 6",

      country: "Lebanon",
      city: "Dbayeh",
      language: "Arabic",
      channel: "Social Media",
      birthdate: "1990-02-01",
      worksInSales: true,
      createdAt: "2024-06-05T10:10:00Z",
    },
    {
      id: 8,
      fullName: "Rania Abdul",
      class: "Supplier",
      roles: ["supplier"],
      type: "Individual",
      category: "General",
      email: "rania.abdul@alignbrokerage.co",
      number: "+974 5 668 1200",
      status: "Active",
      picture: avatar4,
      connections: [
        {
          contactId: 5,
          contactName: "Align Brokerage",
          isPrimary: true,
          relation: "Employer",
        },
        {
          contactId: 2,
          contactName: "Farah Mansour",
          isPrimary: false,
          relation: "Key Client",
        },
      ],
      accounting: {
        taxId: "QA-991122",
        crn: "CRN-2255",
        vatNumber: "VAT-667788",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "The Gate Mall Offices",

      country: "Qatar",
      city: "Doha",
      language: "English",
      channel: "Direct Sales",
      birthdate: "1984-09-18",
      worksInSales: true,
      createdAt: "2024-05-18T09:05:00Z",
    },
    {
      id: 9,
      fullName: "Imad Khoury",
      class: "Contact",
      type: "Individual",
      category: "VIP",
      email: "imad.khoury@financepros.co",
      number: "+961 1 880 441",
      status: "Dormant",
      picture: avatar5,
      connections: [
        {
          contactId: 2,
          contactName: "Farah Mansour",
          isPrimary: true,
          relation: "Client",
        },
        {
          contactId: 6,
          contactName: "Daniel Smith",
          isPrimary: false,
          relation: "Colleague",
        },
      ],
      accounting: {
        taxId: "LB-445566",
        crn: "CRN-3322",
        vatNumber: "VAT-221144",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "Verdun Street 12",

      country: "Lebanon",
      city: "Beirut",
      language: "Arabic",
      channel: "Referral",
      birthdate: "1979-01-10",
      worksInSales: false,
      createdAt: "2024-04-12T16:25:00Z",
    },
    {
      id: 10,
      fullName: "Yara Ghandour",
      class: "Client",
      roles: ["client"],
      type: "Individual",
      category: "VIP",
      email: "yara.ghandour@luxproperties.me",
      number: "+961 70 888 102",
      status: "Lost",
      picture: avatar6,
      connections: [
        {
          contactId: 7,
          contactName: "Mona Darwich",
          isPrimary: true,
          relation: "Partner",
        },
        {
          contactId: 1,
          contactName: "Lina Haddad",
          isPrimary: false,
          relation: "Advisor",
        },
      ],
      accounting: {
        vatNumber: "VAT-909090",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "Furn El Chebbak, Block 4",

      country: "Lebanon",
      city: "Beirut",
      language: "Arabic",
      channel: "Social Media",
      birthdate: "1988-08-30",
      worksInSales: false,
      createdAt: "2024-03-20T11:35:00Z",
    },
    // Added contacts (fully populated)
    {
      id: 11,
      fullName: "Ted Samaha",
      class: "Lead",
      type: "Individual",
      category: "General",
      email: "ted.samaha@squarely.com",
      number: "+961 71 102 110",
      status: "Active",
      picture: avatar1,
      connections: [
        {
          contactId: 3,
          contactName: "Squarely HQ",
          isPrimary: true,
          relation: "Founder",
        },
        {
          contactId: 1,
          contactName: "Lina Haddad",
          isPrimary: false,
          relation: "Product Lead",
        },
      ],
      accounting: {
        taxId: "LB-771234",
        crn: "CRN-8811",
        vatNumber: "VAT-445566",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "Flat 5B, Gemmayzeh Road, Beirut",

      country: "Lebanon",
      city: "Beirut",
      language: "English",
      channel: "Referral",
      birthdate: "1989-05-12",
      worksInSales: true,
      createdAt: "2025-10-01T08:30:00Z",
    },
    {
      id: 12,
      fullName: "Diana Trix",
      class: "Client",
      roles: ["client"],
      type: "Individual",
      category: "Real Estate",
      email: "diana.trix@triareal.com",
      number: "+971 50 900 1222",
      status: "Active",
      picture: avatar2,
      connections: [
        {
          contactId: 5,
          contactName: "Align Brokerage",
          isPrimary: true,
          relation: "Primary Broker",
        },
        {
          contactId: 2,
          contactName: "Farah Mansour",
          isPrimary: false,
          relation: "Account Manager",
        },
      ],
      accounting: {
        taxId: "AE-992211",
        crn: "CRN-5566",
        vatNumber: "VAT-112211",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "Office 1203, Marina Plaza, Dubai",

      country: "United Arab Emirates",
      city: "Dubai",
      language: "English",
      channel: "Direct Sales",
      birthdate: "1991-09-03",
      worksInSales: false,
      createdAt: "2025-09-20T10:00:00Z",
    },
    {
      id: 13,
      fullName: "Pierre Tannous",
      class: "Supplier",
      roles: ["supplier"],
      type: "Individual",
      category: "VIP",
      email: "pierre.tannous@tannousconsult.com",
      number: "+961 70 210 213",
      status: "Active",
      picture: avatar3,
      connections: [
        {
          contactId: 6,
          contactName: "Daniel Smith",
          isPrimary: true,
          relation: "Strategic Advisor",
        },
        {
          contactId: 9,
          contactName: "Imad Khoury",
          isPrimary: false,
          relation: "Finance Partner",
        },
      ],
      accounting: {
        taxId: "LB-334477",
        crn: "CRN-6622",
        vatNumber: "VAT-776655",
      },
      documents: [],
      records: [],
      address: "Rmeil St, Downtown Beirut, Office 7",

      country: "Lebanon",
      city: "Beirut",
      language: "French",
      channel: "Email Campaigns",
      birthdate: "1984-02-18",
      worksInSales: false,
      createdAt: "2025-08-12T09:45:00Z",
    },
    {
      id: 14,
      fullName: "Alex Chi",
      class: "Contact",
      type: "Individual",
      category: "General",
      email: "alex.chi@techbridge.io",
      number: "+44 20 7111 2233",
      status: "Potential",
      picture: "",
      connections: [
        {
          contactId: 6,
          contactName: "Daniel Smith",
          isPrimary: true,
          relation: "Consultant",
        },
        {
          contactId: 13,
          contactName: "Pierre Tannous",
          isPrimary: false,
          relation: "Partner",
        },
      ],
      accounting: {},
      documents: [],
      records: [],
      address: "Unit 4, King's Cross Business Centre, London",

      country: "United Kingdom",
      city: "London",
      language: "English",
      channel: "Website",
      birthdate: "1990-12-02",
      worksInSales: false,
      createdAt: "2025-07-15T11:20:00Z",
    },
    {
      id: 15,
      fullName: "Nora Farouk",
      class: "Client",
      roles: ["client", "supplier"],
      type: "Individual",
      category: "Real Estate",
      email: "nora.farouk@faroukproperties.me",
      number: "+961 71 330 155",
      status: "Active",
      picture: "",
      connections: [
        {
          contactId: 2,
          contactName: "Farah Mansour",
          isPrimary: true,
          relation: "Account Manager",
        },
        {
          contactId: 5,
          contactName: "Align Brokerage",
          isPrimary: false,
          relation: "Preferred Broker",
        },
      ],
      accounting: {
        taxId: "LB-441100",
        crn: "CRN-9900",
        vatNumber: "VAT-223344",
      },
      documents: [],
      records: [],
      address: "Sea View Tower, Furn El Chebbak, Apt 22",

      country: "Lebanon",
      city: "Beirut",
      language: "Arabic",
      channel: "Social Media",
      birthdate: "1987-11-21",
      worksInSales: false,
      createdAt: "2025-06-30T14:00:00Z",
    },
    {
      id: 16,
      fullName: "Omar Haddad",
      class: "Contact",
      type: "Individual",
      category: "General",
      email: "omar.haddad@haddadgroup.com",
      number: "+961 70 220 016",
      status: "Active",
      picture: "",
      connections: [
        {
          contactId: 1,
          contactName: "Lina Haddad",
          isPrimary: true,
          relation: "Brother",
        },
        {
          contactId: 3,
          contactName: "Squarely HQ",
          isPrimary: false,
          relation: "Vendor",
        },
      ],
      accounting: {},
      documents: [],
      records: [],
      address: "Mar Mikhael, Building 12, Beirut",

      country: "Lebanon",
      city: "Beirut",
      language: "Arabic",
      channel: "Referral",
      birthdate: "1986-04-05",
      worksInSales: true,
      createdAt: "2025-05-12T09:30:00Z",
    },
    {
      id: 17,
      fullName: "Lina Azar",
      class: "Contact",
      type: "Individual",
      category: "General",
      email: "lina.azar@azarconsults.com",
      number: "+961 70 440 117",
      status: "Potential",
      picture: "",
      connections: [
        {
          contactId: 11,
          contactName: "Ted Samaha",
          isPrimary: true,
          relation: "Business Partner",
        },
        {
          contactId: 7,
          contactName: "Mona Darwich",
          isPrimary: false,
          relation: "Mentor",
        },
      ],
      accounting: {},
      documents: [],
      records: [],
      address: "Jounieh Highway, Bloc C, Apt 3",

      country: "Lebanon",
      city: "Jounieh",
      language: "Arabic",
      channel: "Website",
      birthdate: "1993-03-09",
      worksInSales: false,
      createdAt: "2025-04-22T08:15:00Z",
    },
  ],
};
