import type { ExpenseRecord } from "./types";

export const database: ExpenseRecord[] = [
  {
    expense: {
      id: 1,
      billNumber: "BILL-1",
      billDate: "2026-04-12",
      supplier: {
        id: 15,
        name: "Nora Farouk",
        email: "nora.farouk@faroukproperties.me",
        phone: "+961 71 330 155",
        address: "Sea View Tower, Furn El Chebbak, Apt 22",
      },
      category: "Office Supplies",
      supplierInvoiceNumber: "NF-4821",
      amount: 185,
      balance: 125,
      status: "Partially Paid",
      attachmentName: "office-supplies-apr.pdf",
      attachmentFileKey: null,
      paidAt: null,
      avatar: null,
      paymentMethod: "Bank Transfer",
    },
    payments: [
      {
        id: "expense-payment-1",
        voucherNumber: "PV-1001",
        amount: 60,
        date: "2026-04-13",
        method: "Bank Transfer",
        note: "Partial transfer on first payment run.",
        createdAt: "2026-04-13T10:30:00Z",
        balanceBefore: 185,
        balanceAfter: 125,
      },
    ],
    note: "Nora Farouk | Office Supplies | INV NF-4821 | 2026-04-12 | $185",
  },
  {
    expense: {
      id: 2,
      billNumber: "BILL-2",
      billDate: "2026-04-10",
      supplier: {
        id: 8,
        name: "Rania Abdul",
        email: "rania.abdul@alignbrokerage.co",
        phone: "+974 5 668 1200",
        address: "The Gate Mall Offices",
      },
      category: "Transport",
      supplierInvoiceNumber: "",
      amount: 74,
      balance: 74,
      status: "Flagged",
      attachmentName: null,
      attachmentFileKey: null,
      paidAt: null,
      avatar: null,
      paymentMethod: "Cash",
    },
    payments: [],
    note: "Rania Abdul | Transport | 2026-04-10 | $74",
  },
  {
    expense: {
      id: 3,
      billNumber: "BILL-3",
      billDate: "2026-04-08",
      supplier: {
        id: 13,
        name: "Pierre Tannous",
        email: "pierre.tannous@tannousconsult.com",
        phone: "+961 70 210 213",
        address: "Rmeil St, Downtown Beirut, Office 7",
      },
      category: "Professional Services",
      supplierInvoiceNumber: "PT-2026-044",
      amount: 420,
      balance: 0,
      status: "Paid",
      attachmentName: null,
      attachmentFileKey: null,
      paidAt: "2026-04-09",
      avatar: null,
      paymentMethod: "Cash",
    },
    payments: [
      {
        id: "expense-payment-2",
        voucherNumber: "PV-1002",
        amount: 420,
        date: "2026-04-09",
        method: "Cash",
        note: "Settled at pickup.",
        createdAt: "2026-04-09T13:15:00Z",
        balanceBefore: 420,
        balanceAfter: 0,
      },
    ],
    note:
      "Pierre Tannous | Professional Services | INV PT-2026-044 | 2026-04-08 | $420",
  },
];
