import type { DealProperties } from "./types";

interface DB {
  deals: DealProperties[];
}

export const db: DB = {
  deals: [
    {
      id: 1,
      name: "Boutique Fit-out",
      code: "DL-1",
      amount: 15850,
      projectCode: "PRJ-24018",
      projectName: "Jumeirah Boutique Launch",
      relatedTo: 1,
      type: "Retail",
      estimatedDeliveryDate: "2026-05-20",
      stage: "Negotiation",
      important: true,
      location: "Dubai",
      collaborators: [1, 2, 3],
      note: "Client wants phased delivery around store launch.",
      customFieldValues: {
        additional_field_1: 15850,
        additional_field_2: "Ted",
      },
      items: [
        {
          id: 1,
          name: "Atlas Executive Workstation",
          itemTypeLabel: "Produced Product",
          category: "Desks",
          catalogueItemId: "produced-product-1",
          catalogueType: "Produced Product",
          discountPercent: 0,
          taxApplicable: true,
          quantity: 4,
          unitPrice: 2450,
          status: "Quoted",
          note: "Custom-built executive workstation manufactured in-house for client fit-outs.",
        },
        {
          id: 2,
          name: "Reception Lounge Chair",
          itemTypeLabel: "Product",
          category: "Seating",
          catalogueItemId: "product-1",
          catalogueType: "Product",
          discountPercent: 5,
          taxApplicable: true,
          quantity: 10,
          unitPrice: 420,
          status: "Pending approval",
          note: "Compact upholstered lounge chair for reception and waiting areas.",
        },
        {
          id: 3,
          name: "Decorative Wall Finish Installation",
          itemTypeLabel: "Onetime Service",
          category: "Wall Finishes",
          catalogueItemId: "onetime-service-1",
          catalogueType: "Onetime Service",
          discountPercent: 0,
          taxApplicable: true,
          quantity: 1,
          unitPrice: 1850,
          status: "Quoted",
          note: "One-off decorative wall finish scope for a specified area and agreed handover date.",
        },
      ],
      documents: [
        {
          id: 1,
          category: "PDF",
          type: "Proposal",
          name: "Boutique Fit-out Proposal",
          note: "Initial proposal shared with client",
          fileUrl: "https://example.com/deals/dl-1-proposal.pdf",
          createdAt: "2026-04-11T10:15:00Z",
        },
      ],
      financials: [
        {
          id: 1,
          title: "Quotation QT-1001",
          type: "quotation",
          amount: 15850,
          status: "Sent",
          dueDate: "2026-05-02",
          createdAt: "2026-04-11T09:00:00Z",
        },
        {
          id: 2,
          title: "Deposit request",
          type: "payment",
          amount: 4755,
          status: "Pending",
          dueDate: "2026-05-05",
          createdAt: "2026-04-15T12:00:00Z",
        },
      ],
      createdAt: "2026-04-10T09:30:00Z",
    },
    {
      id: 2,
      name: "Showroom Refresh",
      code: "DL-2",
      amount: 4280,
      projectCode: "SR-908",
      projectName: "Riyadh North Showroom",
      relatedTo: 5,
      type: "Wholesale",
      estimatedDeliveryDate: "2026-06-05",
      stage: "Under Review",
      important: false,
      location: "Riyadh",
      collaborators: [2, 4],
      note: "Pending final material palette approval.",
      customFieldValues: {
        additional_field_1: 4280,
        additional_field_2: "Nora",
      },
      items: [
        {
          id: 1,
          name: "Architectural Lighting Maintenance Contract",
          itemTypeLabel: "Contractual Service",
          category: "Architectural",
          catalogueItemId: "contractual-service-1",
          catalogueType: "Contractual Service",
          discountPercent: 0,
          taxApplicable: true,
          quantity: 1,
          unitPrice: 3200,
          status: "Review",
          note: "Annual maintenance contract covering inspection, cleaning, and minor lighting repairs.",
        },
        {
          id: 2,
          name: "Decorative Pendant Rental Kit",
          itemTypeLabel: "Rental",
          category: "Decorative",
          catalogueItemId: "rental-1",
          catalogueType: "Rental",
          discountPercent: 0,
          taxApplicable: false,
          quantity: 6,
          unitPrice: 180,
          status: "Review",
          note: "Short-term pendant lighting kit available for staged events and temporary installs.",
        },
      ],
      documents: [],
      financials: [
        {
          id: 1,
          title: "Quotation QT-1002",
          type: "quotation",
          amount: 4280,
          status: "Draft",
          dueDate: "2026-05-09",
          createdAt: "2026-04-15T08:30:00Z",
        },
      ],
      createdAt: "2026-04-14T13:15:00Z",
    },
    {
      id: 3,
      name: "Corporate Event Package",
      code: "DL-3",
      amount: 7680,
      projectCode: null,
      projectName: "June Activation Package",
      relatedTo: 3,
      type: "Retail",
      estimatedDeliveryDate: "2026-05-12",
      stage: "In Progress",
      important: true,
      location: "Online",
      collaborators: [1, 3, 4],
      note: "Fast turnaround requested for June activation.",
      customFieldValues: {
        additional_field_1: 7680,
        additional_field_2: "Maya",
      },
      items: [
        {
          id: 1,
          name: "Workplace Acoustic Consulting Retainer",
          itemTypeLabel: "Retainer Service",
          category: "Acoustic Panels",
          catalogueItemId: "retainer-service-1",
          catalogueType: "Retainer Service",
          discountPercent: 0,
          taxApplicable: false,
          quantity: 3,
          unitPrice: 1500,
          status: "In production",
          note: "Monthly acoustic consulting retainer for ongoing workplace planning and review.",
        },
        {
          id: 2,
          name: "Monthly Meeting Pod Cleaning Service",
          itemTypeLabel: "Recurrent Service",
          category: "Meeting Pods",
          catalogueItemId: "reccurent-service-1",
          catalogueType: "Reccurent Service",
          discountPercent: 0,
          taxApplicable: false,
          quantity: 6,
          unitPrice: 260,
          status: "Ready",
          note: "Recurring monthly cleaning and upkeep service for enclosed meeting pods.",
        },
        {
          id: 3,
          name: "Indoor Planter Set",
          itemTypeLabel: "Product",
          category: "Planters",
          catalogueItemId: "product-2",
          catalogueType: "Product",
          discountPercent: 0,
          taxApplicable: true,
          quantity: 12,
          unitPrice: 135,
          status: "Ready",
          note: "Indoor planter set with liners for lobbies, corridors, and breakout spaces.",
        },
      ],
      documents: [
        {
          id: 1,
          category: "PDF",
          type: "Proposal",
          name: "Corporate Event Scope",
          note: "Approved event scope and budget",
          fileUrl: "https://example.com/deals/dl-3-scope.pdf",
          createdAt: "2026-04-19T09:10:00Z",
        },
      ],
      financials: [
        {
          id: 1,
          title: "Quotation QT-1003",
          type: "quotation",
          amount: 7680,
          status: "Approved",
          dueDate: "2026-04-28",
          createdAt: "2026-04-19T09:00:00Z",
        },
        {
          id: 2,
          title: "Advance payment",
          type: "payment",
          amount: 3840,
          status: "Received",
          dueDate: "2026-04-25",
          createdAt: "2026-04-22T11:45:00Z",
        },
      ],
      createdAt: "2026-04-18T08:00:00Z",
    },
  ],
};
