import type { DealProperties } from './types'

interface DB {
  deals: DealProperties[]
}

export const db: DB = {
  deals: [
    {
      id: 1,
      name: 'Boutique Fit-out',
      code: 'DL-1001',
      relatedTo: 1,
      type: 'Retail',
      estimatedDeliveryDate: '2026-05-20',
      stage: 'Negotiation',
      important: true,
      location: 'Dubai',
      collaborators: [1, 3, 6],
      note: 'Client wants phased delivery around store launch.',
      customFieldValues: {
        additional_field_1: 180000,
        additional_field_2: 'Ted',
      },
      items: [
        {
          id: 1,
          name: 'Storefront signage package',
          quantity: 1,
          unitPrice: 45000,
          status: 'Quoted',
          note: 'Includes fabrication and installation',
        },
        {
          id: 2,
          name: 'Feature display shelving',
          quantity: 6,
          unitPrice: 12000,
          status: 'Pending approval',
          note: 'Walnut finish requested by client',
        },
      ],
      documents: [
        {
          id: 1,
          category: 'PDF',
          type: 'Proposal',
          name: 'Boutique Fit-out Proposal',
          note: 'Initial proposal shared with client',
          fileUrl: 'https://example.com/deals/dl-1001-proposal.pdf',
          createdAt: '2026-04-11T10:15:00Z',
        },
      ],
      financials: [
        {
          id: 1,
          title: 'Quotation QT-1001',
          type: 'quotation',
          amount: 180000,
          status: 'Sent',
          dueDate: '2026-05-02',
          createdAt: '2026-04-11T09:00:00Z',
        },
        {
          id: 2,
          title: 'Deposit request',
          type: 'payment',
          amount: 54000,
          status: 'Pending',
          dueDate: '2026-05-05',
          createdAt: '2026-04-15T12:00:00Z',
        },
      ],
      createdAt: '2026-04-10T09:30:00Z',
    },
    {
      id: 2,
      name: 'Showroom Refresh',
      code: 'DL-1002',
      relatedTo: 5,
      type: 'Wholesale',
      estimatedDeliveryDate: '2026-06-05',
      stage: 'Under Review',
      important: false,
      location: 'Riyadh',
      collaborators: [2, 5],
      note: 'Pending final material palette approval.',
      customFieldValues: {
        additional_field_1: 92000,
        additional_field_2: 'Nora',
      },
      items: [
        {
          id: 1,
          name: 'Lighting refresh package',
          quantity: 1,
          unitPrice: 30000,
          status: 'Review',
          note: 'Awaiting electrical load confirmation',
        },
      ],
      documents: [],
      financials: [
        {
          id: 1,
          title: 'Quotation QT-1002',
          type: 'quotation',
          amount: 92000,
          status: 'Draft',
          dueDate: '2026-05-09',
          createdAt: '2026-04-15T08:30:00Z',
        },
      ],
      createdAt: '2026-04-14T13:15:00Z',
    },
    {
      id: 3,
      name: 'Corporate Event Package',
      code: 'DL-1003',
      relatedTo: 3,
      type: 'Retail',
      estimatedDeliveryDate: '2026-05-12',
      stage: 'In Progress',
      important: true,
      location: 'Online',
      collaborators: [3, 7, 9],
      note: 'Fast turnaround requested for June activation.',
      customFieldValues: {
        additional_field_1: 45000,
        additional_field_2: 'Maya',
      },
      items: [
        {
          id: 1,
          name: 'Branded backdrop',
          quantity: 2,
          unitPrice: 9000,
          status: 'In production',
          note: 'Final artwork approved',
        },
        {
          id: 2,
          name: 'Registration desk setup',
          quantity: 1,
          unitPrice: 6500,
          status: 'Ready',
          note: 'Storage and transport included',
        },
      ],
      documents: [
        {
          id: 1,
          category: 'PDF',
          type: 'Proposal',
          name: 'Corporate Event Scope',
          note: 'Approved event scope and budget',
          fileUrl: 'https://example.com/deals/dl-1003-scope.pdf',
          createdAt: '2026-04-19T09:10:00Z',
        },
      ],
      financials: [
        {
          id: 1,
          title: 'Quotation QT-1003',
          type: 'quotation',
          amount: 45000,
          status: 'Approved',
          dueDate: '2026-04-28',
          createdAt: '2026-04-19T09:00:00Z',
        },
        {
          id: 2,
          title: 'Advance payment',
          type: 'payment',
          amount: 22500,
          status: 'Received',
          dueDate: '2026-04-25',
          createdAt: '2026-04-22T11:45:00Z',
        },
      ],
      createdAt: '2026-04-18T08:00:00Z',
    },
  ],
}
