import type { DealProperties, DealSalesTaskTemplate } from "./types";
import { seedEmployeeId } from "@/utils/seedIdentityGraph";

interface DB {
  deals: DealProperties[];
}

const salesTask = (
  id: number,
  title: string,
  afterWhen: string | null,
  notes = "",
  sourceItemId: number | null = null,
  sourceTaskId: number | null = null,
): DealSalesTaskTemplate => ({
  id,
  title,
  collaborators: [],
  afterWhen,
  startTrigger: null,
  manhours: null,
  notes,
  status: "pending",
  important: false,
  attachment: null,
  relatedTo: null,
  steps: [],
  sourceItemId,
  sourceTaskId,
});

export const db: DB = {
  deals: [
    {
      id: 1,
      name: "Boutique Fit-out",
      code: "DL01",
      amount: 15880,
      projectCode: "PRJ-24018",
      projectName: "Jumeirah Boutique Launch",
      relatedTo: 1,
      linkedJobId: null,
      salesman: seedEmployeeId.rania,
      type: "Retail",
      estimatedDeliveryDate: "2026-05-20",
      stage: "Negotation",
      important: true,
      location: "Dubai",
      collaborators: [
        seedEmployeeId.omar,
        seedEmployeeId.rania,
        seedEmployeeId.karim,
      ],
      note: "Client wants phased delivery around store launch.",
      customFieldValues: {
        additional_field_1: 15880,
        additional_field_2: "Ted",
      },
      notes: [
        {
          id: "deal-1-note-1",
          body: "Client approved the commercial direction and requested the decorative primer as a visible line item.",
          authorName: "Lina Haddad",
          createdAt: "2026-04-11T08:45:00Z",
        },
        {
          id: "deal-1-note-2",
          body: "Production drawing must be checked before procurement starts.",
          authorName: "Maya Rahal",
          createdAt: "2026-04-12T14:20:00Z",
        },
      ],
      items: [
        {
          id: 1,
          name: "Atlas Executive Workstation",
          itemTypeLabel: "Produced Product",
          category: "Desks",
          catalogueItemId: "produced-product-1",
          catalogueType: "Produced Product",
          parentItemId: null,
          sourceRelatedItemId: null,
          removedPhaseIds: null,
          customPhases: null,
          excludedRelatedItemIds: null,
          subItemOverrides: null,
          discountPercent: 0,
          taxApplicable: true,
          quantity: 4,
          unitPrice: 2450,
          status: "Quoted",
          note: "Custom-built executive workstation manufactured in-house for client fit-outs.",
        },
        {
          id: 2,
          name: "Reception Lounge Chair",
          itemTypeLabel: "Product",
          category: "Seating",
          catalogueItemId: "product-1",
          catalogueType: "Product",
          parentItemId: null,
          sourceRelatedItemId: null,
          removedPhaseIds: null,
          customPhases: null,
          excludedRelatedItemIds: null,
          subItemOverrides: null,
          discountPercent: 5,
          taxApplicable: true,
          quantity: 10,
          unitPrice: 420,
          status: "Pending approval",
          note: "Compact upholstered lounge chair for reception and waiting areas.",
        },
        {
          id: 3,
          name: "Decorative Wall Finish Installation",
          itemTypeLabel: "Onetime Service",
          category: "Wall Finishes",
          catalogueItemId: "onetime-service-1",
          catalogueType: "Onetime Service",
          parentItemId: null,
          sourceRelatedItemId: null,
          removedPhaseIds: null,
          customPhases: null,
          excludedRelatedItemIds: [],
          subItemOverrides: {
            "related-1": {
              name: "Decorative Primer Coat",
              category: "Wall Finishes",
              quantity: 1,
              unitPrice: 240,
              discountPercent: 0,
              taxApplicable: true,
              note: "Required primer before final decorative finish.",
            },
          },
          discountPercent: 0,
          taxApplicable: true,
          quantity: 1,
          unitPrice: 1850,
          status: "Quoted",
          note: "One-off decorative wall finish scope for a specified area and agreed handover date.",
        },
        {
          id: 4,
          name: "Decorative Primer Coat",
          itemTypeLabel: "Related Item",
          category: "Wall Finishes",
          catalogueItemId: null,
          catalogueType: "Related Item",
          parentItemId: 3,
          sourceRelatedItemId: 1,
          removedPhaseIds: null,
          customPhases: null,
          excludedRelatedItemIds: null,
          subItemOverrides: null,
          discountPercent: 0,
          taxApplicable: true,
          quantity: 1,
          unitPrice: 240,
          status: "Quoted",
          note: "Preparation layer required before the final finish.",
        },
      ],
      salesTasks: [
        salesTask(
          1,
          "Review production drawing",
          "+1 day",
          "Validate finish and cable-access selections before fabrication.",
          1,
          1,
        ),
        salesTask(2, "Site inspection", "+1 day", "", 3, 1),
        salesTask(3, "Client finish approval", "+1 week", "", 3, 2),
      ],
      documents: [
        {
          id: 1,
          category: "PDF",
          type: "Proposal",
          name: "Boutique Fit-out Proposal",
          note: "Initial proposal shared with client",
          fileUrl: "https://example.com/deals/dl01-proposal.pdf",
          createdAt: "2026-04-11T10:15:00Z",
        },
      ],
      financials: [
        {
          id: 1,
          title: "Quotation QT-1001",
          type: "quotation",
          amount: 15880,
          status: "Sent",
          dueDate: "2026-05-02",
          createdAt: "2026-04-11T09:00:00Z",
        },
        {
          id: 2,
          title: "Deposit request",
          type: "payment",
          amount: 4764,
          status: "Pending",
          dueDate: "2026-05-05",
          createdAt: "2026-04-15T12:00:00Z",
        },
      ],
      createdAt: "2026-04-10T09:30:00Z",
      updatedAt: "2026-04-18T15:00:00Z",
    },
    {
      id: 2,
      name: "Showroom Refresh",
      code: "DL02",
      amount: 4280,
      projectCode: "SR-908",
      projectName: "Riyadh North Showroom",
      relatedTo: 5,
      linkedJobId: null,
      salesman: seedEmployeeId.omar,
      type: "Wholesale",
      estimatedDeliveryDate: "2026-06-05",
      stage: "Pre-Sale",
      pendingStageTransition: {
        targetStage: "Negotation",
        reason: "Sales manager requested approval to move showroom refresh into negotiation.",
        event: "quotation-created",
        requestedAt: "2026-06-26T08:40:00Z",
      },
      important: false,
      location: "Riyadh",
      collaborators: [seedEmployeeId.karim, seedEmployeeId.sara],
      note: "Pending final material palette approval.",
      customFieldValues: {
        additional_field_1: 4280,
        additional_field_2: "Nora",
      },
      notes: [
        {
          id: "deal-2-note-1",
          body: "Maintenance scope split into mobilization and preventive maintenance phases for staged billing.",
          authorName: "Karim Haddad",
          createdAt: "2026-04-15T10:05:00Z",
        },
      ],
      items: [
        {
          id: 1,
          name: "Architectural Lighting Maintenance Contract",
          itemTypeLabel: "Contractual Service",
          category: "Architectural",
          catalogueItemId: "contractual-service-1",
          catalogueType: "Contractual Service",
          parentItemId: null,
          sourceRelatedItemId: null,
          removedPhaseIds: [],
          customPhases: [
            {
              id: "custom-emergency-callout",
              name: "Emergency Callout Allowance",
              category: "Architectural",
              quantity: 1,
              price: 350,
              discountPercent: 0,
              taxApplicable: true,
              note: "Optional allowance requested by facilities team.",
            },
          ],
          excludedRelatedItemIds: null,
          subItemOverrides: {
            "phase-1": {
              name: "Mobilization",
              category: "Architectural",
              quantity: 1,
              unitPrice: 950,
              discountPercent: 0,
              taxApplicable: true,
              note: "Adjusted to include night access coordination.",
            },
            "phase-2": {
              name: "Preventive Maintenance",
              category: "Architectural",
              quantity: 1,
              unitPrice: 2250,
              discountPercent: 0,
              taxApplicable: true,
              note: "Quarterly inspection and minor corrective works.",
            },
          },
          discountPercent: 0,
          taxApplicable: true,
          quantity: 1,
          unitPrice: 3200,
          status: "Review",
          note: "Annual maintenance contract covering inspection, cleaning, and minor lighting repairs.",
        },
        {
          id: 2,
          name: "Decorative Pendant Rental Kit",
          itemTypeLabel: "Rental",
          category: "Decorative",
          catalogueItemId: "rental-1",
          catalogueType: "Rental",
          parentItemId: null,
          sourceRelatedItemId: null,
          removedPhaseIds: null,
          customPhases: null,
          excludedRelatedItemIds: null,
          subItemOverrides: null,
          discountPercent: 0,
          taxApplicable: false,
          quantity: 6,
          unitPrice: 180,
          status: "Review",
          note: "Short-term pendant lighting kit available for staged events and temporary installs.",
        },
      ],
      salesTasks: [
        salesTask(1, "Review contract scope", "+1 day", "", 1, 1),
        salesTask(2, "Confirm maintenance calendar", "+1 month", "", 1, 2),
      ],
      documents: [],
      financials: [
        {
          id: 1,
          title: "Quotation QT-1002",
          type: "quotation",
          amount: 4280,
          status: "Draft",
          dueDate: "2026-05-09",
          createdAt: "2026-04-15T08:30:00Z",
        },
      ],
      createdAt: "2026-04-14T13:15:00Z",
      updatedAt: "2026-04-16T09:40:00Z",
    },
    {
      id: 3,
      name: "Corporate Event Package",
      code: "DL03",
      amount: 7680,
      projectCode: null,
      projectName: "June Activation Package",
      relatedTo: 3,
      linkedJobId: null,
      salesman: seedEmployeeId.omar,
      type: "Retail",
      estimatedDeliveryDate: "2026-05-12",
      stage: "Active",
      important: true,
      location: "Online",
      collaborators: [
        seedEmployeeId.omar,
        seedEmployeeId.rania,
        seedEmployeeId.layla,
      ],
      note: "Fast turnaround requested for June activation.",
      customFieldValues: {
        additional_field_1: 7680,
        additional_field_2: "Maya",
      },
      notes: [
        {
          id: "deal-3-note-1",
          body: "Retainer and recurrent rows include billable period metadata so document generation can bill one month at a time.",
          authorName: "Layla Saab",
          createdAt: "2026-04-19T12:30:00Z",
        },
      ],
      items: [
        {
          id: 1,
          name: "Workplace Acoustic Consulting Retainer",
          itemTypeLabel: "Retainer Service",
          category: "Acoustic Panels",
          catalogueItemId: "retainer-service-1",
          catalogueType: "Retainer Service",
          parentItemId: null,
          sourceRelatedItemId: null,
          removedPhaseIds: null,
          customPhases: [
            {
              id: "retainer-custom-reporting",
              name: "Monthly Reporting Pack",
              category: "Acoustic Panels",
              quantity: 1,
              price: 250,
              discountPercent: 0,
              taxApplicable: true,
              note: "Extra monthly reporting requested by the client.",
            },
          ],
          excludedRelatedItemIds: null,
          subItemOverrides: {
            "retainer-1": {
              name: "Monthly Acoustic Review",
              category: "Acoustic Panels",
              quantity: 1,
              unitPrice: 1500,
              periodUnitPrices: {
                "monthly:2026-05": 1500,
                "monthly:2026-06": 1500,
                "monthly:2026-07": 1500,
              },
              discountPercent: 0,
              taxApplicable: false,
              note: "Scheduled workplace acoustic review and recommendations.",
            },
          },
          discountPercent: 0,
          taxApplicable: false,
          quantity: 1,
          retainerStartDate: "2026-05-01",
          retainerEndDate: "2026-07-31",
          retainerPeriods: 3,
          retainerBillablePeriods: 3,
          unitPrice: 1500,
          status: "In production",
          note: "Monthly acoustic consulting retainer for ongoing workplace planning and review.",
        },
        {
          id: 2,
          name: "Monthly Meeting Pod Cleaning Service",
          itemTypeLabel: "Reccurent Service",
          category: "Meeting Pods",
          catalogueItemId: "reccurent-service-1",
          catalogueType: "Reccurent Service",
          parentItemId: null,
          sourceRelatedItemId: null,
          removedPhaseIds: null,
          customPhases: null,
          excludedRelatedItemIds: null,
          subItemOverrides: {
            "recurrent-1": {
              name: "Monthly Pod Cleaning Visit",
              category: "Meeting Pods",
              quantity: 1,
              unitPrice: 260,
              periodUnitPrices: {
                "monthly:2026-05": 260,
                "monthly:2026-06": 260,
                "monthly:2026-07": 260,
                "monthly:2026-08": 260,
                "monthly:2026-09": 260,
                "monthly:2026-10": 260,
              },
              discountPercent: 0,
              taxApplicable: false,
              note: "Recurring scheduled cleaning visit for meeting pods.",
            },
          },
          discountPercent: 0,
          taxApplicable: false,
          quantity: 1,
          recurrentStartDate: "2026-05-01",
          recurrentEndDate: "2026-10-31",
          recurrentPeriods: 6,
          recurrentBillablePeriods: 6,
          unitPrice: 260,
          status: "Ready",
          note: "Recurring monthly cleaning and upkeep service for enclosed meeting pods.",
        },
        {
          id: 3,
          name: "Indoor Planter Set",
          itemTypeLabel: "Product",
          category: "Planters",
          catalogueItemId: "product-2",
          catalogueType: "Product",
          parentItemId: null,
          sourceRelatedItemId: null,
          removedPhaseIds: null,
          customPhases: null,
          excludedRelatedItemIds: null,
          subItemOverrides: null,
          discountPercent: 0,
          taxApplicable: true,
          quantity: 12,
          unitPrice: 135,
          status: "Ready",
          note: "Indoor planter set with liners for lobbies, corridors, and breakout spaces.",
        },
      ],
      salesTasks: [salesTask(1, "Confirm retainer scope", "+1 week", "", 1, 1)],
      documents: [
        {
          id: 1,
          category: "PDF",
          type: "Proposal",
          name: "Corporate Event Scope",
          note: "Approved event scope and budget",
          fileUrl: "https://example.com/deals/dl03-scope.pdf",
          createdAt: "2026-04-19T09:10:00Z",
        },
      ],
      financials: [
        {
          id: 1,
          title: "Quotation QT-1003",
          type: "quotation",
          amount: 7680,
          status: "Approved",
          dueDate: "2026-04-28",
          createdAt: "2026-04-19T09:00:00Z",
        },
        {
          id: 2,
          title: "Advance payment",
          type: "payment",
          amount: 3840,
          status: "Received",
          dueDate: "2026-04-25",
          createdAt: "2026-04-22T11:45:00Z",
        },
      ],
      createdAt: "2026-04-18T08:00:00Z",
      updatedAt: "2026-04-23T11:45:00Z",
    },
  ],
};
