import avatar1 from "@images/avatars/avatar-1.png";
import avatar2 from "@images/avatars/avatar-2.png";
import avatar3 from "@images/avatars/avatar-3.png";
import avatar4 from "@images/avatars/avatar-4.png";

import type { EmployeeProperties } from "./types";

interface DB {
  users: EmployeeProperties[];
}

export const db: DB = {
  users: [
    {
      id: 1,
      fullName: "Lina Haddad",
      class: undefined,
      category: undefined,
      email: "lina.haddad@example.com",
      number: "+961 70 123 456",
      status: "Active",
      picture: avatar1,
      accounting: {
        taxId: "LB-123456",
        crn: "CRN-9981",
        vatNumber: "VAT-112233",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "123 Downtown Street",
      country: "Lebanon",
      city: "Beirut",
      language: "Arabic",
      channel: "Referral",
      website: "https://lina.example.com",
      birthdate: "1987-04-15",
      worksInSales: true,
      createdAt: "2024-09-01T09:00:00Z",
      employment: {
        department: "Sales",
        reportToIds: [3, 2],
        contractStatus: "draft",
        startDate: "2024-09-01",
        endDate: null,
        contracts: [
          {
            id: 1,
            salaryPaid: "Monthly",
            employmentType: "Full-time",
            startDate: "2024-09-01",
            probationEndDate: "2024-12-01",
            firstPayroll: "2024-09-30",
            note: "Initial contract for sales position",
            status: "Active",
            createdAt: "2024-09-01T09:00:00Z",
          },
        ],
      },
      salary: { base: 4200, currency: "USD", memberOfSalesTeam: true },
      paymentMethods: [],
      requests: [],
    },
    {
      id: 2,
      fullName: "Farah Mansour",
      class: undefined,
      category: undefined,
      email: "client.services@cedarholdings.com",
      number: "+971 4 445 2233",
      status: "Active",
      picture: avatar2,
      accounting: {
        taxId: "AE-449120",
        crn: "CRN-2045",
        vatNumber: "VAT-8877",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "Dubai Marina, Al Seef Tower",
      country: "UAE",
      city: "Dubai",
      language: "English",
      channel: "Referral",
      website: "https://cedarholdings.example.com",
      birthdate: "1982-11-30",
      worksInSales: false,
      createdAt: "2024-08-15T11:30:00Z",
      employment: {
        department: "Operations",
        reportToIds: [],
        contractStatus: "draft",
        startDate: "2024-08-15",
        endDate: null,
        contracts: [
          {
            id: 2,
            salaryPaid: "Monthly",
            employmentType: "Full-time",
            startDate: "2024-08-15",
            probationEndDate: "2024-11-15",
            firstPayroll: "2024-08-31",
            note: "Operations manager contract",
            status: "Active",
            createdAt: "2024-08-15T11:30:00Z",
          },
        ],
      },
      salary: { base: 5600, currency: "USD", memberOfSalesTeam: false },
      paymentMethods: [],
      requests: [],
    },
    {
      id: 3,
      fullName: "Daniel Smith",
      class: undefined,
      category: undefined,
      email: "daniel.smith@smithlegal.com",
      number: "+961 71 987 654",
      status: "Not Hired",
      picture: avatar3,
      accounting: {
        taxId: "LB-998877",
        crn: "CRN-5544",
        vatNumber: "VAT-4455",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "Hamra Street",
      country: "Lebanon",
      city: "Beirut",
      language: "English",
      channel: "Direct Sales",
      website: "https://smithlegal.example.com",
      birthdate: "1979-02-10",
      worksInSales: false,
      createdAt: "2024-07-20T14:10:00Z",
      employment: {
        department: "Legal",
        reportToIds: [],
        contractStatus: "draft",
        startDate: "2024-07-20",
        endDate: null,
        contracts: [],
      },
      salary: null,
      paymentMethods: [],
      requests: [],
    },
    {
      id: 4,
      fullName: "Rana Khoury",
      class: undefined,
      category: undefined,
      email: "rana.khoury@example.com",
      number: "+961 3 456 789",
      status: "Not Hired",
      picture: avatar4,
      accounting: { taxId: "", crn: "", vatNumber: "" },
      documents: [],
      records: [],
      transactions: [],
      address: "Jounieh Main Rd",
      country: "Lebanon",
      city: "Jounieh",
      language: "French",
      channel: "Website",
      website: "",
      birthdate: "1993-12-05",
      worksInSales: false,
      createdAt: "2025-01-02T09:00:00Z",
      employment: {
        department: "Finance",
        reportToIds: [2, 3],
        contractStatus: "draft",
        startDate: "2025-01-02",
        endDate: null,
        contracts: [],
      },
      salary: null,
      paymentMethods: [],
      requests: [],
    },
  ],
};
