import avatar1 from "@images/avatars/avatar-1.png";
import avatar2 from "@images/avatars/avatar-2.png";
import avatar3 from "@images/avatars/avatar-3.png";
import avatar4 from "@images/avatars/avatar-4.png";

import type { EmployeeProperties, EmployeeRequest } from "./types";
import { seedIdentities } from "@/utils/seedIdentityGraph";

interface DB {
  users: EmployeeProperties[];
}

export const db: DB = {
  users: [
    {
      id: 1,
      fullName: "Lina Haddad",
      class: undefined,
      category: undefined,
      email: "lina.haddad@example.com",
      number: "+961 70 123 456",
      status: "Active",
      picture: avatar1,
      accounting: {
        taxId: "LB-123456",
        crn: "CRN-9981",
        vatNumber: "VAT-112233",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "123 Downtown Street",
      country: "Lebanon",
      city: "Beirut",
      language: "Arabic",
      channel: "Referral",
      website: "https://lina.example.com",
      birthdate: "1987-04-15",
      worksInSales: true,
      createdAt: "2024-09-01T09:00:00Z",
      employment: {
        department: "Sales",
        reportToIds: [3, 2],
        contractStatus: "draft",
        startDate: "2024-09-01",
        endDate: null,
        isSalesTeamMember: true,
        salesPercentage: 5,
        salesAmount: 0,
        contracts: [
          {
            id: 1,
            salaryPaid: "Monthly",
            employmentType: "Full-time",
            startDate: "2024-09-01",
            probationEndDate: "2024-12-01",
            firstPayroll: "2024-09-30",
            note: "Initial contract for sales position",
            status: "Active",
            createdAt: "2024-09-01T09:00:00Z",
          },
        ],
        positions: [
          {
            id: 1,
            position: "Sales Representative",
            startingDate: "2024-09-01",
            note: "Initial sales position",
            createdAt: "2024-09-01T09:00:00Z",
          },
        ],
      },
      salary: {
        currency: "USD",
        history: [
          {
            id: 1,
            basicSalary: 3500,
            transportation: 300,
            housing: 300,
            allowance: 100,
            date: "01-09-2024",
            startingPeriod: "September - 2024",
            note: "Initial salary",
            createdAt: "2024-09-01T09:00:00Z",
          },
          {
            id: 2,
            basicSalary: 4000,
            transportation: 350,
            housing: 350,
            allowance: 150,
            date: "01-11-2024",
            startingPeriod: "November - 2024",
            note: "Performance raise after 2 months",
            createdAt: "2024-11-01T09:00:00Z",
          },
        ],
      },
      paymentMethods: [
        {
          id: 1,
          type: "Bank Transfer",
          bankName: "Bank Audi",
          branchName: "Downtown Beirut",
          accountName: "Lina Haddad",
          accountNumber: "123456789",
          iban: "LB62 0999 0000 0001 0019 0122 9114",
          swiftCode: "AUDBLBBX",
          isPrimary: true,
          createdAt: "2024-09-01T09:00:00Z",
        },
        {
          id: 2,
          type: "Cash",
          isPrimary: false,
          createdAt: "2024-10-15T14:30:00Z",
        },
      ],
      requests: [
        {
          id: 1,
          type: "Leave",
          typeId: "vacation",
          startDate: "2025-12-20",
          returnDate: "2025-12-27",
          requestedDays: 5,
          deductible: true,
          periodId: "December - 2025",
          deductionAmount: 5,
          reason: "Family vacation during holidays",
          attachmentFile: "",
          attachmentLink: "https://docs.google.com/",
          status: "pending",
          createdAt: "2025-11-20T10:30:00Z",
        },
        {
          id: 2,
          type: "Addition",
          additionType: "bonus",
          date: "2025-11-15",
          amount: 500,
          period: "November - 2025",
          relatedType: "Not Linked",
          relatedId: undefined,
          notes: "Performance bonus for Q4 sales targets",
          attachmentFile: "",
          attachmentLink: "",
          status: "approved",
          createdAt: "2025-11-10T14:20:00Z",
          approvedBy: 3,
          approvedAt: "2025-11-12T09:15:00Z",
        },
        {
          id: 3,
          type: "Time au Lieu",
          numberOfDays: 2,
          date: "2025-11-25",
          relatedTo: "Not Linked",
          relatedId: undefined,
          note: "Worked overtime during project launch",
          status: "pending",
          createdAt: "2025-11-25T16:45:00Z",
        },
      ],
      attendance: {
        vacation: 21,
        sickLeave: 14,
        parentalLeave: 90,
        carryoverDays: 5,
        workSchedule: {
          Monday: { active: true, remote: false, from: "09:00", to: "18:00" },
          Tuesday: { active: true, remote: true, from: "09:00", to: "18:00" },
          Wednesday: {
            active: true,
            remote: false,
            from: "09:00",
            to: "18:00",
          },
          Thursday: { active: true, remote: false, from: "09:00", to: "18:00" },
          Friday: { active: true, remote: false, from: "09:00", to: "17:00" },
          Saturday: {
            active: false,
            remote: false,
            from: "09:00",
            to: "17:00",
          },
          Sunday: { active: false, remote: false, from: "09:00", to: "17:00" },
        },
        allowedExtraTime: 20,
      },
    },
    {
      id: 2,
      fullName: "Farah Mansour",
      class: undefined,
      category: undefined,
      email: "client.services@cedarholdings.com",
      number: "+971 4 445 2233",
      status: "Active",
      picture: avatar2,
      accounting: {
        taxId: "AE-449120",
        crn: "CRN-2045",
        vatNumber: "VAT-8877",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "Dubai Marina, Al Seef Tower",
      country: "UAE",
      city: "Dubai",
      language: "English",
      channel: "Referral",
      website: "https://cedarholdings.example.com",
      birthdate: "1982-11-30",
      worksInSales: false,
      createdAt: "2024-08-15T11:30:00Z",
      employment: {
        department: "Operations",
        reportToIds: [],
        contractStatus: "draft",
        startDate: "2024-08-15",
        endDate: null,
        isSalesTeamMember: false,
        salesPercentage: 0,
        salesAmount: 0,
        contracts: [
          {
            id: 2,
            salaryPaid: "Monthly",
            employmentType: "Full-time",
            startDate: "2024-08-15",
            probationEndDate: "2024-11-15",
            firstPayroll: "2024-08-31",
            note: "Operations manager contract",
            status: "Active",
            createdAt: "2024-08-15T11:30:00Z",
          },
        ],
        positions: [
          {
            id: 1,
            position: "Operations Manager",
            startingDate: "2024-08-15",
            note: "Leading operations team",
            createdAt: "2024-08-15T11:30:00Z",
          },
        ],
      },
      salary: {
        currency: "USD",
        history: [
          {
            id: 1,
            basicSalary: 5000,
            transportation: 250,
            housing: 250,
            allowance: 100,
            date: "15-08-2024",
            startingPeriod: "August - 2024",
            note: "Starting salary as Operations Manager",
            createdAt: "2024-08-15T11:30:00Z",
          },
        ],
      },
      paymentMethods: [
        {
          id: 1,
          type: "Bank Transfer",
          bankName: "Emirates NBD",
          branchName: "Dubai Marina",
          accountName: "Farah Mansour",
          accountNumber: "987654321",
          iban: "AE07 0331 2345 6789 0123 456",
          swiftCode: "EBILAEAD",
          isPrimary: true,
          createdAt: "2024-08-15T11:30:00Z",
        },
      ],
      requests: [
        {
          id: 1,
          type: "Deduction",
          deductionType: "late-arrival",
          date: "2025-11-18",
          amount: 100,
          period: "November - 2025",
          notes: "Late arrival on 3 occasions",
          attachmentFile: "",
          attachmentLink: "",
          status: "approved",
          createdAt: "2025-11-18T11:30:00Z",
          approvedBy: 3,
          approvedAt: "2025-11-19T10:00:00Z",
        },
        {
          id: 2,
          type: "Advance",
          advanceType: "salary-advance",
          date: "2025-11-10",
          amount: 2000,
          payBackInMonths: 4,
          startOfPaymentPeriod: "December - 2025",
          notes: "Emergency medical expenses",
          attachmentFile: "",
          attachmentLink: "https://docs.google.com/",
          status: "pending",
          createdAt: "2025-11-10T09:20:00Z",
        },
        {
          id: 3,
          type: "Leave",
          typeId: "sick-leave",
          startDate: "2025-12-05",
          returnDate: "2025-12-06",
          requestedDays: 1,
          deductible: false,
          periodId: "December - 2025",
          deductionAmount: 0,
          reason: "Medical appointment",
          attachmentFile: "",
          attachmentLink: "",
          status: "draft",
          createdAt: "2025-11-26T15:10:00Z",
        },
        {
          id: 4,
          type: "Leave",
          typeId: "vacation",
          startDate: "2025-08-21",
          returnDate: "2025-08-21",
          requestedDays: 5,
          deductible: true,
          periodId: "August - 2025",
          deductionAmount: 5,
          reason: "nnnnnnnn",
          attachmentFile: "",
          attachmentLink: "",
          status: "pending",
          createdAt: "2025-08-21T10:00:00Z",
        },
        {
          id: 5,
          type: "Addition",
          additionType: "overtime",
          date: "2025-10-15",
          amount: 450,
          period: "October - 2025",
          relatedType: "project",
          relatedId: 1,
          notes: "Overtime for project deadline",
          attachmentFile: "",
          attachmentLink: "",
          status: "approved",
          createdAt: "2025-10-15T18:30:00Z",
          approvedBy: 3,
          approvedAt: "2025-10-16T09:00:00Z",
        },
        {
          id: 6,
          type: "Leave",
          typeId: "vacation",
          startDate: "2025-06-12",
          returnDate: "2025-06-18",
          requestedDays: 4,
          deductible: true,
          periodId: "June - 2025",
          deductionAmount: 4,
          reason: "Family vacation",
          attachmentFile: "",
          attachmentLink: "",
          status: "approved",
          createdAt: "2025-06-12T08:00:00Z",
          approvedBy: 3,
          approvedAt: "2025-06-13T10:30:00Z",
        },
        {
          id: 7,
          type: "Time au Lieu",
          numberOfDays: 2,
          date: "2025-09-22",
          relatedTo: "overtime",
          relatedId: 3,
          note: "Compensation for weekend work on system migration",
          status: "approved",
          createdAt: "2025-09-22T14:00:00Z",
          approvedBy: 3,
          approvedAt: "2025-09-23T09:15:00Z",
        },
        {
          id: 8,
          type: "Addition",
          additionType: "bonus",
          date: "2025-07-30",
          amount: 800,
          period: "July - 2025",
          relatedType: "performance",
          relatedId: 2,
          notes: "Q2 performance bonus",
          attachmentFile: "",
          attachmentLink: "",
          status: "approved",
          createdAt: "2025-07-30T12:00:00Z",
          approvedBy: 3,
          approvedAt: "2025-07-31T08:00:00Z",
        },
        {
          id: 9,
          type: "Leave",
          typeId: "sick-leave",
          startDate: "2025-03-10",
          returnDate: "2025-03-12",
          requestedDays: 3,
          deductible: false,
          periodId: "March - 2025",
          deductionAmount: 0,
          reason: "Flu",
          attachmentFile: "",
          attachmentLink: "",
          status: "approved",
          createdAt: "2025-03-10T07:30:00Z",
          approvedBy: 3,
          approvedAt: "2025-03-10T09:00:00Z",
        },
        {
          id: 10,
          type: "Advance",
          advanceType: "emergency-advance",
          date: "2025-05-20",
          amount: 1500,
          payBackInMonths: 3,
          startOfPaymentPeriod: "June - 2025",
          notes: "Home repair expenses",
          attachmentFile: "",
          attachmentLink: "",
          status: "approved",
          createdAt: "2025-05-20T11:00:00Z",
          approvedBy: 3,
          approvedAt: "2025-05-21T10:00:00Z",
        },
        {
          id: 11,
          type: "Deduction",
          deductionType: "absence",
          date: "2025-04-08",
          amount: 250,
          period: "April - 2025",
          notes: "Unauthorized absence",
          attachmentFile: "",
          attachmentLink: "",
          status: "approved",
          createdAt: "2025-04-08T16:00:00Z",
          approvedBy: 3,
          approvedAt: "2025-04-09T08:30:00Z",
        },
        {
          id: 12,
          type: "Leave",
          typeId: "vacation",
          startDate: "2025-02-14",
          returnDate: "2025-02-16",
          requestedDays: 2,
          deductible: true,
          periodId: "February - 2025",
          deductionAmount: 2,
          reason: "Personal matters",
          attachmentFile: "",
          attachmentLink: "",
          status: "rejected",
          createdAt: "2025-02-10T09:00:00Z",
          rejectedBy: 3,
          rejectedAt: "2025-02-11T10:00:00Z",
          rejectionReason: "Insufficient notice period",
        },
      ],
      attendance: {
        vacation: 25,
        sickLeave: 14,
        parentalLeave: 120,
        carryoverDays: 8,
        workSchedule: {
          Monday: { active: true, remote: true, from: "08:30", to: "17:30" },
          Tuesday: { active: true, remote: false, from: "08:30", to: "17:30" },
          Wednesday: {
            active: true,
            remote: false,
            from: "08:30",
            to: "17:30",
          },
          Thursday: { active: true, remote: false, from: "08:30", to: "17:30" },
          Friday: { active: true, remote: true, from: "08:30", to: "16:30" },
          Saturday: {
            active: false,
            remote: false,
            from: "09:00",
            to: "17:00",
          },
          Sunday: { active: false, remote: false, from: "09:00", to: "17:00" },
        },
        allowedExtraTime: 30,
      },
    },
    {
      id: 3,
      fullName: "Daniel Smith",
      class: undefined,
      category: undefined,
      email: "daniel.smith@smithlegal.com",
      number: "+961 71 987 654",
      status: "Active",
      picture: avatar3,
      accounting: {
        taxId: "LB-998877",
        crn: "CRN-5544",
        vatNumber: "VAT-4455",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "Hamra Street",
      country: "Lebanon",
      city: "Beirut",
      language: "English",
      channel: "Direct Sales",
      website: "https://smithlegal.example.com",
      birthdate: "1979-02-10",
      worksInSales: false,
      createdAt: "2024-07-20T14:10:00Z",
      employment: {
        department: "Legal",
        reportToIds: [],
        contractStatus: "draft",
        startDate: "2024-07-20",
        endDate: null,
        isSalesTeamMember: false,
        salesPercentage: 0,
        salesAmount: 0,
        contracts: [
          {
            id: 1,
            salaryPaid: "Monthly",
            employmentType: "Full-time",
            startDate: "2024-07-20",
            probationEndDate: "2024-10-20",
            firstPayroll: "2024-07-31",
            note: "Legal advisor contract",
            status: "Active",
            createdAt: "2024-07-20T14:10:00Z",
          },
        ],
        positions: [
          {
            id: 1,
            position: "Legal Advisor",
            startingDate: "2024-07-20",
            note: "Handles legal matters and contracts",
            createdAt: "2024-07-20T14:10:00Z",
          },
        ],
      },
      salary: {
        currency: "USD",
        history: [
          {
            id: 1,
            basicSalary: 4500,
            transportation: 200,
            housing: 400,
            allowance: 150,
            date: "20-07-2024",
            startingPeriod: "July - 2024",
            note: "Initial salary package",
            createdAt: "2024-07-20T14:10:00Z",
          },
        ],
      },
      paymentMethods: [
        {
          id: 1,
          type: "Bank Transfer",
          bankName: "BLOM Bank",
          branchName: "Hamra",
          accountName: "Daniel Smith",
          accountNumber: "555123789",
          iban: "LB92 0017 0000 0000 0053 9010 1300",
          swiftCode: "BLOMLBBX",
          isPrimary: true,
          createdAt: "2024-07-20T14:10:00Z",
        },
      ],
      requests: [
        {
          id: 1,
          type: "Leave",
          typeId: "vacation",
          startDate: "2025-12-24",
          returnDate: "2026-01-03",
          requestedDays: 7,
          deductible: true,
          periodId: "December - 2025",
          deductionAmount: 7,
          reason: "Year-end vacation",
          attachmentFile: "",
          attachmentLink: "",
          status: "rejected",
          createdAt: "2025-11-15T13:45:00Z",
          rejectedBy: 2,
          rejectedAt: "2025-11-16T10:30:00Z",
          rejectionReason: "Critical project deadline during this period",
        },
        {
          id: 2,
          type: "Addition",
          additionType: "overtime",
          date: "2025-11-20",
          amount: 350,
          period: "November - 2025",
          relatedType: "Not Linked",
          relatedId: undefined,
          notes: "Weekend work on legal documentation",
          attachmentFile: "",
          attachmentLink: "",
          status: "approved",
          createdAt: "2025-11-20T17:00:00Z",
          approvedBy: 2,
          approvedAt: "2025-11-21T09:00:00Z",
        },
        {
          id: 3,
          type: "Deduction",
          deductionType: "equipment-damage",
          date: "2025-11-22",
          amount: 150,
          period: "November - 2025",
          notes: "Laptop screen damage",
          attachmentFile: "",
          attachmentLink: "",
          status: "pending",
          createdAt: "2025-11-22T14:30:00Z",
        },
      ],
      attendance: {
        vacation: 22,
        sickLeave: 12,
        parentalLeave: 90,
        carryoverDays: 10,
        workSchedule: {
          Monday: { active: true, remote: false, from: "09:30", to: "18:00" },
          Tuesday: { active: true, remote: false, from: "09:30", to: "18:00" },
          Wednesday: { active: true, remote: true, from: "09:30", to: "18:00" },
          Thursday: { active: true, remote: true, from: "09:30", to: "18:00" },
          Friday: { active: true, remote: false, from: "09:30", to: "17:00" },
          Saturday: {
            active: false,
            remote: false,
            from: "09:00",
            to: "17:00",
          },
          Sunday: { active: false, remote: false, from: "09:00", to: "17:00" },
        },
        allowedExtraTime: 15,
      },
    },
    {
      id: 4,
      fullName: "Rana Khoury",
      class: undefined,
      category: undefined,
      email: "rana.khoury@example.com",
      number: "+961 3 456 789",
      status: "Not Hired",
      picture: avatar4,
      accounting: {
        taxId: "LB-445566",
        crn: "CRN-7788",
        vatNumber: "VAT-9900",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "Jounieh Main Rd",
      country: "Lebanon",
      city: "Jounieh",
      language: "French",
      channel: "Website",
      website: "",
      birthdate: "1993-12-05",
      worksInSales: false,
      createdAt: "2024-10-15T09:00:00Z",
      employment: {
        department: undefined,
        reportToIds: [],
        contractStatus: "draft",
        startDate: null,
        endDate: null,
        isSalesTeamMember: false,
        salesPercentage: 0,
        salesAmount: 0,
        contracts: [],
        positions: [],
      },
      salary: null,
      paymentMethods: [],
      requests: [],
    },
  ],
};

const seededEmployeeRequests: Record<number, EmployeeRequest[]> = {
  1: [
    {
      id: 101,
      type: "Leave",
      typeId: "Vacation",
      startDate: "2026-07-06",
      returnDate: "2026-07-08",
      requestedDays: 2,
      deductible: true,
      periodId: "July - 2026",
      reason: "Family appointment",
      status: "pending",
      createdAt: "2026-06-26T08:15:00Z",
    },
    {
      id: 102,
      type: "Deduction",
      deductionType: "Expense correction",
      date: "2026-06-26",
      amount: 75,
      period: "June - 2026",
      notes: "Parking expense correction for dashboard testing.",
      status: "pending",
      createdAt: "2026-06-26T09:10:00Z",
    },
  ],
  2: [
    {
      id: 201,
      type: "Advance",
      advanceType: "Salary advance",
      date: "2026-06-26",
      amount: 500,
      payBackInMonths: 2,
      startOfPaymentPeriod: "July - 2026",
      notes: "Pending manager approval from Lina.",
      status: "pending",
      createdAt: "2026-06-26T07:45:00Z",
    },
  ],
  3: [
    {
      id: 301,
      type: "Time au Lieu",
      numberOfDays: 1,
      date: "2026-06-27",
      relatedTo: "Weekend support",
      note: "HR weekend onboarding support.",
      status: "pending",
      createdAt: "2026-06-26T10:05:00Z",
    },
  ],
  5: [
    {
      id: 501,
      type: "Addition",
      additionType: "Commission adjustment",
      date: "2026-06-26",
      amount: 250,
      period: "June - 2026",
      relatedType: "Deal",
      relatedId: "DL01",
      notes: "Sales commission adjustment pending Lina approval.",
      status: "pending",
      createdAt: "2026-06-26T11:20:00Z",
    },
  ],
  9: [
    {
      id: 901,
      type: "Leave",
      typeId: "Sick",
      startDate: "2026-06-30",
      returnDate: "2026-07-01",
      requestedDays: 1,
      deductible: false,
      periodId: "June - 2026",
      reason: "Medical checkup",
      status: "pending",
      createdAt: "2026-06-26T12:00:00Z",
    },
  ],
};

const canonicalEmployee = (identity: (typeof seedIdentities)[number]): EmployeeProperties => ({
  id: identity.id,
  fullName: identity.fullName,
  email: identity.email,
  number: `+961 70 900 ${String(identity.id).padStart(3, "0")}`,
  status: "Active",
  picture: identity.avatar,
  accounting: {
    taxId: `EMP-${String(identity.id).padStart(4, "0")}`,
    crn: `HR-${String(identity.id).padStart(4, "0")}`,
    vatNumber: `VAT-HR-${String(identity.id).padStart(4, "0")}`,
  },
  documents: [],
  records: [
    {
      id: identity.id,
      type: "note",
      title: `${identity.roleName} onboarding`,
      body: `${identity.fullName} is seeded as the ${identity.roleName} test account.`,
      author: {
        id: 1,
        name: "Lina Haddad",
      },
      attachments: [],
      createdAt: "2026-01-05T09:00:00Z",
    },
  ],
  transactions: [],
  address: "Squarely Center",
  country: "Lebanon",
  city: "Beirut",
  language: "English",
  channel: identity.worksInSales ? "Direct Sales" : "Referral",
  website: "https://squarely.internal",
  worksInSales: identity.worksInSales,
  createdAt: "2026-01-01T09:00:00Z",
  department: identity.department,
  employment: {
    department: identity.department,
    reportToIds: identity.reportToIds,
    contractStatus: "active",
    startDate: "2026-01-01",
    endDate: null,
    isSalesTeamMember: identity.isSalesTeamMember,
    salesPercentage: identity.isSalesTeamMember ? 5 : 0,
    salesAmount: 0,
    contracts: [
      {
        id: identity.id,
        salaryPaid: "Monthly",
        employmentType: "Full-time",
        startDate: "2026-01-01",
        probationEndDate: "2026-04-01",
        firstPayroll: "2026-01-31",
        note: `${identity.roleName} seed contract`,
        status: "Active",
        createdAt: "2026-01-01T09:00:00Z",
      },
    ],
    positions: [
      {
        id: identity.id,
        position: identity.roleName,
        startingDate: "2026-01-01",
        note: "Canonical ACL seed position",
        createdAt: "2026-01-01T09:00:00Z",
      },
    ],
  },
  salary: {
    currency: "USD",
    history: [
      {
        id: identity.id,
        basicSalary: 3000 + identity.id * 250,
        transportation: 250,
        housing: 250,
        allowance: 100,
        date: "01-01-2026",
        startingPeriod: "January - 2026",
        note: "Canonical seed salary",
        createdAt: "2026-01-01T09:00:00Z",
      },
    ],
  },
  paymentMethods: [],
  attendance: {
    vacation: 21,
    sickLeave: 14,
    parentalLeave: 60,
    carryoverDays: 0,
    workSchedule: {
      Monday: { active: true, remote: false, from: "09:00", to: "18:00" },
      Tuesday: { active: true, remote: false, from: "09:00", to: "18:00" },
      Wednesday: { active: true, remote: false, from: "09:00", to: "18:00" },
      Thursday: { active: true, remote: false, from: "09:00", to: "18:00" },
      Friday: { active: true, remote: true, from: "09:00", to: "17:00" },
      Saturday: { active: false, remote: false, from: "09:00", to: "17:00" },
      Sunday: { active: false, remote: false, from: "09:00", to: "17:00" },
    },
    allowedExtraTime: 12,
  },
  requests: seededEmployeeRequests[identity.id] ?? [],
});

db.users = seedIdentities.map(canonicalEmployee);
