import avatar1 from "@images/avatars/avatar-1.png";
import avatar2 from "@images/avatars/avatar-2.png";
import avatar3 from "@images/avatars/avatar-3.png";
import avatar4 from "@images/avatars/avatar-4.png";

import type { EmployeeProperties } from "./types";

interface DB {
  users: EmployeeProperties[];
}

export const db: DB = {
  users: [
    {
      id: 1,
      fullName: "Lina Haddad",
      class: undefined,
      category: undefined,
      email: "lina.haddad@example.com",
      number: "+961 70 123 456",
      status: "Active",
      picture: avatar1,
      accounting: {
        taxId: "LB-123456",
        crn: "CRN-9981",
        vatNumber: "VAT-112233",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "123 Downtown Street",
      country: "Lebanon",
      city: "Beirut",
      language: "Arabic",
      channel: "Referral",
      website: "https://lina.example.com",
      birthdate: "1987-04-15",
      worksInSales: true,
      createdAt: "2024-09-01T09:00:00Z",
      employment: {
        department: "Sales",
        reportToIds: [3, 2],
        contractStatus: "draft",
        startDate: "2024-09-01",
        endDate: null,
        isSalesTeamMember: true,
        salesPercentage: 5,
        salesAmount: 0,
        contracts: [
          {
            id: 1,
            salaryPaid: "Monthly",
            employmentType: "Full-time",
            startDate: "2024-09-01",
            probationEndDate: "2024-12-01",
            firstPayroll: "2024-09-30",
            note: "Initial contract for sales position",
            status: "Active",
            createdAt: "2024-09-01T09:00:00Z",
          },
        ],
        positions: [
          {
            id: 1,
            position: "Sales Representative",
            startingDate: "2024-09-01",
            note: "Initial sales position",
            createdAt: "2024-09-01T09:00:00Z",
          },
        ],
      },
      salary: {
        currency: "USD",
        history: [
          {
            id: 1,
            basicSalary: 3500,
            transportation: 300,
            housing: 300,
            allowance: 100,
            date: "01-09-2024",
            startingPeriod: "September - 2024",
            note: "Initial salary",
            createdAt: "2024-09-01T09:00:00Z",
          },
          {
            id: 2,
            basicSalary: 4000,
            transportation: 350,
            housing: 350,
            allowance: 150,
            date: "01-11-2024",
            startingPeriod: "November - 2024",
            note: "Performance raise after 2 months",
            createdAt: "2024-11-01T09:00:00Z",
          },
        ],
      },
      paymentMethods: [
        {
          id: 1,
          type: "Bank Transfer",
          bankName: "Bank Audi",
          branchName: "Downtown Beirut",
          accountName: "Lina Haddad",
          accountNumber: "123456789",
          iban: "LB62 0999 0000 0001 0019 0122 9114",
          swiftCode: "AUDBLBBX",
          isPrimary: true,
          createdAt: "2024-09-01T09:00:00Z",
        },
        {
          id: 2,
          type: "Cash",
          isPrimary: false,
          createdAt: "2024-10-15T14:30:00Z",
        },
      ],
      requests: [],
      attendance: {
        vacation: 21,
        sickLeave: 14,
        parentalLeave: 90,
        carryoverDays: 5,
        workSchedule: {
          Monday: { active: true, remote: false, from: "09:00", to: "18:00" },
          Tuesday: { active: true, remote: true, from: "09:00", to: "18:00" },
          Wednesday: {
            active: true,
            remote: false,
            from: "09:00",
            to: "18:00",
          },
          Thursday: { active: true, remote: false, from: "09:00", to: "18:00" },
          Friday: { active: true, remote: false, from: "09:00", to: "17:00" },
          Saturday: {
            active: false,
            remote: false,
            from: "09:00",
            to: "17:00",
          },
          Sunday: { active: false, remote: false, from: "09:00", to: "17:00" },
        },
        allowedExtraTime: 20,
      },
    },
    {
      id: 2,
      fullName: "Farah Mansour",
      class: undefined,
      category: undefined,
      email: "client.services@cedarholdings.com",
      number: "+971 4 445 2233",
      status: "Active",
      picture: avatar2,
      accounting: {
        taxId: "AE-449120",
        crn: "CRN-2045",
        vatNumber: "VAT-8877",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "Dubai Marina, Al Seef Tower",
      country: "UAE",
      city: "Dubai",
      language: "English",
      channel: "Referral",
      website: "https://cedarholdings.example.com",
      birthdate: "1982-11-30",
      worksInSales: false,
      createdAt: "2024-08-15T11:30:00Z",
      employment: {
        department: "Operations",
        reportToIds: [],
        contractStatus: "draft",
        startDate: "2024-08-15",
        endDate: null,
        isSalesTeamMember: false,
        salesPercentage: 0,
        salesAmount: 0,
        contracts: [
          {
            id: 2,
            salaryPaid: "Monthly",
            employmentType: "Full-time",
            startDate: "2024-08-15",
            probationEndDate: "2024-11-15",
            firstPayroll: "2024-08-31",
            note: "Operations manager contract",
            status: "Active",
            createdAt: "2024-08-15T11:30:00Z",
          },
        ],
        positions: [
          {
            id: 1,
            position: "Operations Manager",
            startingDate: "2024-08-15",
            note: "Leading operations team",
            createdAt: "2024-08-15T11:30:00Z",
          },
        ],
      },
      salary: {
        currency: "USD",
        history: [
          {
            id: 1,
            basicSalary: 5000,
            transportation: 250,
            housing: 250,
            allowance: 100,
            date: "15-08-2024",
            startingPeriod: "August - 2024",
            note: "Starting salary as Operations Manager",
            createdAt: "2024-08-15T11:30:00Z",
          },
        ],
      },
      paymentMethods: [
        {
          id: 1,
          type: "Bank Transfer",
          bankName: "Emirates NBD",
          branchName: "Dubai Marina",
          accountName: "Farah Mansour",
          accountNumber: "987654321",
          iban: "AE07 0331 2345 6789 0123 456",
          swiftCode: "EBILAEAD",
          isPrimary: true,
          createdAt: "2024-08-15T11:30:00Z",
        },
      ],
      requests: [],
      attendance: {
        vacation: 25,
        sickLeave: 14,
        parentalLeave: 120,
        carryoverDays: 8,
        workSchedule: {
          Monday: { active: true, remote: true, from: "08:30", to: "17:30" },
          Tuesday: { active: true, remote: false, from: "08:30", to: "17:30" },
          Wednesday: {
            active: true,
            remote: false,
            from: "08:30",
            to: "17:30",
          },
          Thursday: { active: true, remote: false, from: "08:30", to: "17:30" },
          Friday: { active: true, remote: true, from: "08:30", to: "16:30" },
          Saturday: {
            active: false,
            remote: false,
            from: "09:00",
            to: "17:00",
          },
          Sunday: { active: false, remote: false, from: "09:00", to: "17:00" },
        },
        allowedExtraTime: 30,
      },
    },
    {
      id: 3,
      fullName: "Daniel Smith",
      class: undefined,
      category: undefined,
      email: "daniel.smith@smithlegal.com",
      number: "+961 71 987 654",
      status: "Active",
      picture: avatar3,
      accounting: {
        taxId: "LB-998877",
        crn: "CRN-5544",
        vatNumber: "VAT-4455",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "Hamra Street",
      country: "Lebanon",
      city: "Beirut",
      language: "English",
      channel: "Direct Sales",
      website: "https://smithlegal.example.com",
      birthdate: "1979-02-10",
      worksInSales: false,
      createdAt: "2024-07-20T14:10:00Z",
      employment: {
        department: "Legal",
        reportToIds: [],
        contractStatus: "draft",
        startDate: "2024-07-20",
        endDate: null,
        isSalesTeamMember: false,
        salesPercentage: 0,
        salesAmount: 0,
        contracts: [
          {
            id: 1,
            salaryPaid: "Monthly",
            employmentType: "Full-time",
            startDate: "2024-07-20",
            probationEndDate: "2024-10-20",
            firstPayroll: "2024-07-31",
            note: "Legal advisor contract",
            status: "Active",
            createdAt: "2024-07-20T14:10:00Z",
          },
        ],
        positions: [
          {
            id: 1,
            position: "Legal Advisor",
            startingDate: "2024-07-20",
            note: "Handles legal matters and contracts",
            createdAt: "2024-07-20T14:10:00Z",
          },
        ],
      },
      salary: {
        currency: "USD",
        history: [
          {
            id: 1,
            basicSalary: 4500,
            transportation: 200,
            housing: 400,
            allowance: 150,
            date: "20-07-2024",
            startingPeriod: "July - 2024",
            note: "Initial salary package",
            createdAt: "2024-07-20T14:10:00Z",
          },
        ],
      },
      paymentMethods: [
        {
          id: 1,
          type: "Bank Transfer",
          bankName: "BLOM Bank",
          branchName: "Hamra",
          accountName: "Daniel Smith",
          accountNumber: "555123789",
          iban: "LB92 0017 0000 0000 0053 9010 1300",
          swiftCode: "BLOMLBBX",
          isPrimary: true,
          createdAt: "2024-07-20T14:10:00Z",
        },
      ],
      requests: [],
      attendance: {
        vacation: 22,
        sickLeave: 12,
        parentalLeave: 90,
        carryoverDays: 10,
        workSchedule: {
          Monday: { active: true, remote: false, from: "09:30", to: "18:00" },
          Tuesday: { active: true, remote: false, from: "09:30", to: "18:00" },
          Wednesday: { active: true, remote: true, from: "09:30", to: "18:00" },
          Thursday: { active: true, remote: true, from: "09:30", to: "18:00" },
          Friday: { active: true, remote: false, from: "09:30", to: "17:00" },
          Saturday: {
            active: false,
            remote: false,
            from: "09:00",
            to: "17:00",
          },
          Sunday: { active: false, remote: false, from: "09:00", to: "17:00" },
        },
        allowedExtraTime: 15,
      },
    },
    {
      id: 4,
      fullName: "Rana Khoury",
      class: undefined,
      category: undefined,
      email: "rana.khoury@example.com",
      number: "+961 3 456 789",
      status: "Not Hired",
      picture: avatar4,
      accounting: {
        taxId: "LB-445566",
        crn: "CRN-7788",
        vatNumber: "VAT-9900",
      },
      documents: [],
      records: [],
      transactions: [],
      address: "Jounieh Main Rd",
      country: "Lebanon",
      city: "Jounieh",
      language: "French",
      channel: "Website",
      website: "",
      birthdate: "1993-12-05",
      worksInSales: false,
      createdAt: "2024-10-15T09:00:00Z",
      employment: {
        department: null,
        reportToIds: [],
        contractStatus: "draft",
        startDate: null,
        endDate: null,
        isSalesTeamMember: false,
        salesPercentage: 0,
        salesAmount: 0,
        contracts: [],
        positions: [],
      },
      salary: null,
      paymentMethods: [],
      requests: [],
    },
  ],
};
