import type AppConfigurations from "./types";

export interface ConfigDB {
  configurations: AppConfigurations;
}

export const db: ConfigDB = {
  configurations: {
    legal: {
      logo: "/images/avatars/squarely.png",
      companyName: "Squarely LLC",
      crn: "CRN-123456789",
      address: "123 Market Street, Suite 400",
      country: "United States",
      city: "San Francisco",
      number: "+1 (415) 555-1234",
      email: "info@squarely.example",
      website: "https://squarely.example",
      socialLinks: [
        "https://twitter.com/squarely",
        "https://linkedin.com/company/squarely",
      ],
      ownership: [
        { contactId: 1, contactName: "Jane Doe" },
        { contactId: 2, contactName: "John Smith" },
      ],
    },
    financial: {
      currency: "US Dollar (USD $)",
      vat: {
        enabled: true,
        registrationNumber: "VAT-987654321",
        attachDocument: true,
      },
      bankDetails: [
        {
          enabled: true,
          bankName: "Bank of Examples",
          accountName: "Squarely LLC",
          iban: "AE070331234567890123456",
          accountNumber: "1234567890",
          branch: "Downtown",
          swiftCode: "EXAMPL99",
        },
      ],
      invoicing: {
        showNotes: true,
        notesOnInvoice: "Payment due within 30 days.",
        noteOnQuotation: "Prices valid for 14 days from issue date.",
      },
      documentTypes: ["Invoice", "Quotation", "Proforma", "Receipt"],
      invoiceSequence: "INV-YYYY-",
      referenceFormat: "{type}-{seq}",
      skipDeleted: true,
      paymentReminders: {
        enabled: true,
        invoiceDaysBefore: 7,
        purchaseDaysBefore: 10,
      },
      accounts: [
        { id: "acc-1", name: "Cash" },
        { id: "acc-2", name: "Bank" },
        { id: "acc-3", name: "Receivables" },
      ],
    },
    hr: {
      deductions: ["Late Penalty", "Absence", "Salary Adjustment", "Other"],
      additions: ["Overtime", "Bonus", "Reimbursables", "Other"],
      advances: ["Travel Advance", "Salary Advance", "Personal", "Other"],
      leaves: {
        types: [
          "Annual Leave",
          "Sick Leave",
          "Unpaid Leave",
          "Bereavement Leave",
          "Parental Leave",
        ],
        policy: "Annual leave",
        countBasis: "Calendar Days",
        includeNonWorkingDays: true,
      },
      departments: [
        "Management",
        "Sales",
        "Marketing",
        "Operations",
        "Finance",
        "PR Team",
        "Events Team",
      ],

      requestApproval: "one_level",
      reimbursables: ["Fuel", "Meals", "Supplies"],
    },
    crm: {
      DefaultContactType: "Individual",
      organization: {
        category: "B2B",
        requirePhone: true,
        requireEmail: true,
        inactiveAfterMonths: 4,
      },
      individual: {
        category: "B2C",
        requirePhone: false,
        requireEmail: true,
        inactiveAfterMonths: 4,
      },
      individualCategories: [
        "General",
        "VIP",
        "Outsourcing",
        "Apparel & Fashion",
        "Jewelry & Accessories",
        "Architecture & Engineering",
        "Food & Beverage",
        "Gifts & Souvenirs",
        "Books & Stationery",
        "Home & Furniture",
        "Fitness & Wellness",
        "Sporting Goods",
        "Art & Crafts",
        "Automotive",
        "Toys & Hobbies",
        "Pet & Vets",
        "Real Estate",
        "Consultancy",
        "Manufacturing",
        "Events & Entertainment",
        "Travel & Tourism",
        "Baby & Kids",
        "Other",
      ],
      organizationCategories: [
        "General",
        "Repairs",
        "Furniture & Appliances",
        "Travel",
        "Financial Services",
        "Software Provider",
        "Tools & Equipment",
        "Legal & PRO Services",
        "Office Supplies",
        "Payment Processors",
        "Marketing & PR",
        "Shipping & Courier",
        "Email Provider",
      ],
      channels: [
        "Social Media",
        "Referral",
        "Direct Sales",
        "Website",
        "Email Campaign",
      ],
      locations: ["HQ", "Dubai", "Riyadh", "Cairo"],
      documentCategories: [
        "ID",
        "Contract",
        "Tax",
        "License",
        "HR",
        "Finance",
        "Operations",
        "Sales",
        "Other",
      ],
      documentTypes: [
        "Passport",
        "Visa",
        "ID Card",
        "Labor Card",
        "Health Card",
        "Insurance Card",
        "Residency Card",
        "Contract",
        "Tax Registration",
        "Trade License",
        "VAT Certificate",
        "VAT License",
        "Tax License",
        "Payslip",
        "Reimbursements Invoice",
        "Bank Details",
        "SOPs",
        "Proposals",
        "Other",
      ],
      // documentRenewable is stored as 'yes' or 'no'
      documentRenewable: "yes",
      callPurposes: ["Sales", "Follow Up", "Admin", "Other"],
      sentiment: ["Very Good", "Good", "Acceptable", "Poor", "Very Poor"],
      showContactRecord: false,
      notes: ["General", "Ideas", "Blod Articles", "Meeting Notes"],
      meetings: ["Sales", "Brief", "Site Visit", "Other"],
      jobStages: ["PRPSL", "In Review", "Project | In Progress", "RFI"],
      jobAlert: { enabled: true, days: 3 },
    },
    deals: {
      leadLostIn: 30,
      quotationLostIn: 45,
      quotationStartsSeq: "QTN-",
      proformaStartSeq: "PF-",
      salesType: ["Retail", "Wholesale"],
      salesLocation: ["Dubai", "Riyadh", "Online"],
      fieldLabels: { amount: "Deal Amount", owner: "Owner" },
      dealStages: [
        "Under Review",
        "Negotiation",
        "In Progress",
        "High Priority",
        "Express Order",
        "On Hold",
        "Awaiting Payment",
        "Canceled",
        "Completed",
      ],
      dealAlert: { enabled: true, days: 5 },
    },
  },
};

export default db;
